channel_sources:
  - ros-playground,conda-forge,defaults
channel_targets:
  - ros-playground main
c_compiler:                    # [win]
  - vs2017                     # [win]
cxx_compiler:                  # [win]
  - vs2017                     # [win]
python:
  - 3.7
