pkg-config:
  conda: [pkg-config]
python-rospkg:
  conda: [rospkg]
python3-rospkg:
  conda: [rospkg]
boost:
  conda: [boost]
python-argparse:
  conda: []
python-catkin-pkg:
  conda: [catkin_pkg]
python3-catkin-pkg:
  conda: [catkin_pkg]
python:
  conda: [python]
python3:
  conda: [python]
python3-dev:
  conda: [python]
python-rosdep:
  conda: [rosdep]
python3-rosdep:
  conda: [rosdep]
python-empy:
  conda: [empy]
python3-empy:
  conda: [empy]
tinyxml:
  conda: [tinyxml]
tinyxml2:
  conda: [tinyxml2]
gtest:
  conda: [gtest]
cmake:
  conda: [cmake]
google-mock:
  conda: [gmock]
python-mock:
  conda: [mock]
python3-mock:
  conda: [mock]
python-nose:
  conda: [nose]
python3-nose:
  conda: [nose]
python-coverage:
  conda: [coverage]
python3-coverage:
  conda: [coverage]
libconsole-bridge-dev:
  conda: [console_bridge]
python-yaml:
  conda: [pyyaml]
python3-yaml:
  conda: [pyyaml]
python3-setuptools:
  conda: [setuptools]
python3-catkin-pkg-modules:
  conda: [catkin_pkg]
python3-rosdep-modules:
  conda: [rosdep]
libboost-thread-dev:
  conda: [boost]
libboost-system-dev:
  conda: [boost]
libboost-system-dev:
  conda: [boost]
libboost-date-time-dev:
  conda: [boost]
libboost-thread-dev:
  conda: [boost]
libpoco-dev:
  conda: [poco]
python-gnupg:
  conda: [python-gnupg]
python-imaging:
  conda: [pillow]
python-crypto:
  conda: [pycrypto]
bzip2:
  conda: [bzip2]
libssl-dev:
  conda: [openssl]
libgpgme-dev:
  conda: []
log4cxx:
  conda: [log4cxx]
apr:
  conda: [apr]
python-netifaces:
  conda: [netifaces]
python3-netifaces:
  conda: [netifaces]
python-paramiko:
  conda: [paramiko]
sbcl:
  conda: []
lz4:
  conda: [lz4]
python-defusedxml:
  conda: [defusedxml]
python-numpy:
  conda: [numpy]
python3-pytest:
  conda: [pytest]
python3-rosdistro-modules:
  conda: [rosdistro]
python3-lark-parser:
  conda: [lark-parser]
cppcheck:
  conda: [cppcheck]
python3-mypy:
  conda: [mypy]
zlib:
  conda: [zlib]
python3-pkg-resources:
  conda: []
python3-cryptography:
  conda: [cryptography]
python3-numpy:
  conda: [numpy]
python3-ifcfg:
  conda: [ifcfg]
python3-flake8:
  conda: [flake8]
python3-pytest-mock:
  conda: [pytest-mock]
yaml:
  conda: [yaml]
asio:
  conda: [asio]
git:
  conda: [git]
spdlog:
  conda: [spdlog]
pcre:
  conda: [pcre]
pydocstyle:
  conda: [pydocstyle]
libxml2-utils:
  conda: [libxml2]
libcunit-dev:
  conda: []
uncrustify:
  conda: [uncrustify]
python3-lxml:
  conda: [lxml]
openssl:
  conda: [openssl]
eigen:
  conda: [eigen]