package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/rviz-release.git
    git_rev: release/eloquent/rviz2/7.0.4-1
    folder: ros-eloquent-rviz2/src/work
    patches:
      - patch/ros-eloquent-rviz2.patch

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-rviz2
    version: 7.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-rviz-common
        - ros-eloquent-ament-cmake
        - ros-eloquent-rviz-ogre-vendor
        - qt
      run:
        - python
        - ros-eloquent-rviz-common
        - ros-eloquent-rviz-ogre-vendor
        - ros-eloquent-rviz-default-plugins
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
