package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/rmw_implementation-release.git
    git_rev: release/eloquent/rmw_implementation/0.8.2-2
    folder: ros-eloquent-rmw-implementation/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-rmw-implementation
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-rmw-fastrtps-cpp
        - ros-eloquent-poco-vendor
        - poco
        - ros-eloquent-rmw-implementation-cmake
        - ros-eloquent-rcutils
        - ros-eloquent-rmw
        - ros-eloquent-ament-cmake-python
        - ros-eloquent-ament-cmake
      run:
        - python
        - poco
        - ros-eloquent-rmw-implementation-cmake
        - ros-eloquent-poco-vendor
        - ros-eloquent-ament-index-python
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
