package:
  name: ros
  version: 2020.02.26

source:
  - git_url: https://github.com/ros2-gbp/ros_workspace-release.git
    git_rev: release/eloquent/ros_workspace/0.8.0-1
    folder: ros-eloquent-ros-workspace/src/work
    patches:
      - patch/ros-eloquent-ros-workspace.patch

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-ros-workspace
    version: 0.8.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-ament-package
        - colcon-common-extensions
        - python {{ python }}
        - ros-eloquent-ament-cmake-core
        - cmake
      run:
        - python {{ python }}
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
