package:
  name: ros
  version: 2020.02.29

source:
  - git_url: https://github.com/ros2-gbp/variants-release.git
    git_rev: release/eloquent/desktop/0.8.4-1
    folder: ros-eloquent-desktop/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-desktop
    version: 0.8.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
        - python {{ python }}
      run:
        - ros-eloquent-intra-process-demo
        - ros-eloquent-examples-rclcpp-minimal-publisher
        - ros-eloquent-rviz-default-plugins
        - python {{ python }}
        - ros-eloquent-action-tutorials-interfaces
        - ros-eloquent-rqt-common-plugins
        - ros-eloquent-teleop-twist-joy
        - ros-eloquent-teleop-twist-keyboard
        - ros-eloquent-quality-of-service-demo-cpp
        - ros-eloquent-depthimage-to-laserscan
        - ros-eloquent-quality-of-service-demo-py
        - ros-eloquent-demo-nodes-cpp
        - ros-eloquent-examples-rclcpp-minimal-action-client
        - ros-eloquent-action-tutorials-py
        - ros-eloquent-composition
        - ros-eloquent-examples-rclpy-minimal-service
        - ros-eloquent-examples-rclpy-minimal-action-server
        - ros-eloquent-examples-rclpy-minimal-action-client
        - ros-eloquent-examples-rclcpp-minimal-action-server
        - ros-eloquent-demo-nodes-cpp-native
        - ros-eloquent-ros-base
        - ros-eloquent-demo-nodes-py
        - ros-eloquent-dummy-sensors
        - ros-eloquent-examples-rclpy-minimal-publisher
        - ros-eloquent-examples-rclcpp-minimal-subscriber
        - ros-eloquent-dummy-map-server
        - ros-eloquent-examples-rclpy-minimal-client
        - ros-eloquent-joy
        - ros-eloquent-angles
        - ros-eloquent-topic-monitor
        - ros-eloquent-pendulum-msgs
        - ros-eloquent-examples-rclcpp-minimal-timer
        - ros-eloquent-logging-demo
        - ros-eloquent-action-tutorials-cpp
        - ros-eloquent-dummy-robot-bringup
        - ros-eloquent-lifecycle
        - ros-eloquent-image-tools
        - ros-eloquent-examples-rclcpp-minimal-client
        - ros-eloquent-rviz2
        - ros-eloquent-examples-rclcpp-minimal-service
        - ros-eloquent-examples-rclpy-minimal-subscriber
        - ros-eloquent-examples-rclpy-executors
        - ros-eloquent-pcl-conversions
        - ros-eloquent-examples-rclcpp-minimal-composition
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
