package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/poco_vendor-release.git
    git_rev: release/eloquent/poco_vendor/1.2.0-1
    folder: ros-eloquent-poco-vendor/src/work
  - git_url: https://github.com/ros2-gbp/rosidl-release.git
    git_rev: release/eloquent/rosidl_generator_c/0.8.2-1
    folder: ros-eloquent-rosidl-generator-c/src/work
  - git_url: https://github.com/ros2-gbp/rosidl_typesupport-release.git
    git_rev: release/eloquent/rosidl_typesupport_c/0.8.0-2
    folder: ros-eloquent-rosidl-typesupport-c/src/work
  - git_url: https://github.com/ros2-gbp/rosidl-release.git
    git_rev: release/eloquent/rosidl_typesupport_interface/0.8.2-1
    folder: ros-eloquent-rosidl-typesupport-interface/src/work
  - git_url: https://github.com/ros2-gbp/rosidl-release.git
    git_rev: release/eloquent/rosidl_typesupport_introspection_c/0.8.2-1
    folder: ros-eloquent-rosidl-typesupport-introspection-c/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-poco-vendor
    version: 1.2.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - pcre
        - cmake
        - poco
        - zlib
      run:
        - python
        - pcre
        - cmake
        - poco
        - zlib
    script: bld_colcon.bat
  - name: ros-eloquent-rosidl-generator-c
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-rosidl-typesupport-interface
      run:
        - python
        - ros-eloquent-rosidl-cmake
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-typesupport-interface
        - ros-eloquent-rosidl-parser
    script: bld_colcon.bat
  - name: ros-eloquent-rosidl-typesupport-c
    version: 0.8.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-poco-vendor
        - poco
        - ros-eloquent-rosidl-typesupport-introspection-c
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-rosidl-generator-c
      run:
        - python
        - ros-eloquent-poco-vendor
        - poco
        - ros-eloquent-rmw-implementation
        - ros-eloquent-rosidl-typesupport-interface
        - ros-eloquent-rosidl-generator-c
        - ros-eloquent-ament-cmake-core
    script: bld_colcon.bat
  - name: ros-eloquent-rosidl-typesupport-interface
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - python
    script: bld_colcon.bat
  - name: ros-eloquent-rosidl-typesupport-introspection-c
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake-ros
      run:
        - python
        - ros-eloquent-rosidl-cmake
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-generator-c
        - ros-eloquent-rosidl-parser
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
