package:
  name: ros
  version: 2020.03.08

source:
  - git_url: https://github.com/ros-gbp/catkin-release.git
    git_rev: release/noetic/catkin/0.8.1-1
    folder: ros-noetic-catkin/src/work
  - git_url: https://github.com/ros-gbp/roscpp_core-release.git
    git_rev: release/noetic/cpp_common/0.7.1-1
    folder: ros-noetic-cpp-common/src/work
  - git_url: https://github.com/ros-gbp/gencpp-release.git
    git_rev: release/noetic/gencpp/0.6.5-1
    folder: ros-noetic-gencpp/src/work
  - git_url: https://github.com/tork-a/geneus-release.git
    git_rev: release/noetic/geneus/3.0.0-1
    folder: ros-noetic-geneus/src/work
  - git_url: https://github.com/ros-gbp/genlisp-release.git
    git_rev: release/noetic/genlisp/0.4.18-1
    folder: ros-noetic-genlisp/src/work
  - git_url: https://github.com/ros-gbp/genmsg-release.git
    git_rev: release/noetic/genmsg/0.5.15-1
    folder: ros-noetic-genmsg/src/work
  - git_url: https://github.com/sloretz/gennodejs-release.git
    git_rev: release/noetic/gennodejs/2.0.2-1
    folder: ros-noetic-gennodejs/src/work
  - git_url: https://github.com/ros-gbp/genpy-release.git
    git_rev: release/noetic/genpy/0.6.10-1
    folder: ros-noetic-genpy/src/work
  - git_url: https://github.com/ros-gbp/message_generation-release.git
    git_rev: release/noetic/message_generation/0.4.1-1
    folder: ros-noetic-message-generation/src/work
  - git_url: https://github.com/ros-gbp/message_runtime-release.git
    git_rev: release/noetic/message_runtime/0.4.13-1
    folder: ros-noetic-message-runtime/src/work
  - git_url: https://github.com/ros-gbp/roscpp_core-release.git
    git_rev: release/noetic/roscpp_serialization/0.7.1-1
    folder: ros-noetic-roscpp-serialization/src/work
  - git_url: https://github.com/ros-gbp/roscpp_core-release.git
    git_rev: release/noetic/roscpp_traits/0.7.1-1
    folder: ros-noetic-roscpp-traits/src/work
  - git_url: https://github.com/ros-gbp/roscpp_core-release.git
    git_rev: release/noetic/rostime/0.7.1-1
    folder: ros-noetic-rostime/src/work
  - git_url: https://github.com/ros-gbp/std_msgs-release.git
    git_rev: release/noetic/std_msgs/0.5.13-1
    folder: ros-noetic-std-msgs/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-catkin
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - catkin_pkg
        - cmake
        - empy
        - gmock
        - gtest
        - mock
        - nose
        - python {{ python }}
        - setuptools
      run:
        - catkin_pkg
        - cmake
        - empy
        - gmock
        - gtest
        - nose
        - python {{ python }}
        - setuptools
    script: bld_cmake.bat
  - name: ros-noetic-cpp-common
    version: 0.7.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - console_bridge
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - boost
        - console_bridge
        - python {{ python }}
    script: bld_cmake.bat
  - name: ros-noetic-gencpp
    version: 0.6.5
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-genmsg
        - setuptools
      run:
        - python {{ python }}
        - ros-noetic-genmsg
    script: bld_cmake.bat
  - name: ros-noetic-geneus
    version: 3.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-genmsg
        - setuptools
      run:
        - python {{ python }}
        - ros-noetic-genmsg
    script: bld_cmake.bat
  - name: ros-noetic-genlisp
    version: 0.4.18
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-genmsg
        - setuptools
      run:
        - python {{ python }}
        - ros-noetic-genmsg
    script: bld_cmake.bat
  - name: ros-noetic-genmsg
    version: 0.5.15
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - setuptools
      run:
        - empy
        - python {{ python }}
        - ros-noetic-catkin
    script: bld_cmake.bat
  - name: ros-noetic-gennodejs
    version: 2.0.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-genmsg
        - setuptools
      run:
        - python {{ python }}
        - ros-noetic-genmsg
    script: bld_cmake.bat
  - name: ros-noetic-genpy
    version: 0.6.10
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-genmsg
        - setuptools
      run:
        - python {{ python }}
        - pyyaml
        - ros-noetic-genmsg
    script: bld_cmake.bat
  - name: ros-noetic-message-generation
    version: 0.4.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-gencpp
        - ros-noetic-geneus
        - ros-noetic-genlisp
        - ros-noetic-genmsg
        - ros-noetic-gennodejs
        - ros-noetic-genpy
      run:
        - python {{ python }}
        - ros-noetic-gencpp
        - ros-noetic-geneus
        - ros-noetic-genlisp
        - ros-noetic-genmsg
        - ros-noetic-gennodejs
        - ros-noetic-genpy
    script: bld_cmake.bat
  - name: ros-noetic-message-runtime
    version: 0.4.13
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cpp-common
        - ros-noetic-genpy
        - ros-noetic-roscpp-serialization
        - ros-noetic-roscpp-traits
        - ros-noetic-rostime
      run:
        - python {{ python }}
        - ros-noetic-cpp-common
        - ros-noetic-genpy
        - ros-noetic-roscpp-serialization
        - ros-noetic-roscpp-traits
        - ros-noetic-rostime
    script: bld_cmake.bat
  - name: ros-noetic-roscpp-serialization
    version: 0.7.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cpp-common
        - ros-noetic-roscpp-traits
        - ros-noetic-rostime
      run:
        - python {{ python }}
        - ros-noetic-cpp-common
        - ros-noetic-roscpp-traits
        - ros-noetic-rostime
    script: bld_cmake.bat
  - name: ros-noetic-roscpp-traits
    version: 0.7.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cpp-common
        - ros-noetic-rostime
      run:
        - python {{ python }}
        - ros-noetic-cpp-common
        - ros-noetic-rostime
    script: bld_cmake.bat
  - name: ros-noetic-rostime
    version: 0.7.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cpp-common
      run:
        - boost
        - python {{ python }}
        - ros-noetic-cpp-common
    script: bld_cmake.bat
  - name: ros-noetic-std-msgs
    version: 0.5.13
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
      run:
        - python {{ python }}
        - ros-noetic-message-runtime
    script: bld_cmake.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
