package:
  name: ros
  version: 0.0.1

source:
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake
    fn: ros-eloquent-ament-cmake.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_core/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-core
    fn: ros-eloquent-ament-cmake-core.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_export_definitions/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-export-definitions
    fn: ros-eloquent-ament-cmake-export-definitions.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_export_dependencies/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-export-dependencies
    fn: ros-eloquent-ament-cmake-export-dependencies.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_export_include_directories/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-export-include-directories
    fn: ros-eloquent-ament-cmake-export-include-directories.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_export_interfaces/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-export-interfaces
    fn: ros-eloquent-ament-cmake-export-interfaces.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_export_libraries/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-export-libraries
    fn: ros-eloquent-ament-cmake-export-libraries.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_export_link_flags/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-export-link-flags
    fn: ros-eloquent-ament-cmake-export-link-flags.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_include_directories/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-include-directories
    fn: ros-eloquent-ament-cmake-include-directories.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_libraries/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-libraries
    fn: ros-eloquent-ament-cmake-libraries.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_python/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-python
    fn: ros-eloquent-ament-cmake-python.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_target_dependencies/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-target-dependencies
    fn: ros-eloquent-ament-cmake-target-dependencies.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_test/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-test
    fn: ros-eloquent-ament-cmake-test.tar.gz
  - url: https://github.com/ros2-gbp/ament_cmake-release/archive/release/eloquent/ament_cmake_version/0.8.2-1.tar.gz
    folder: ros-eloquent-ament-cmake-version
    fn: ros-eloquent-ament-cmake-version.tar.gz
  - url: https://github.com/ros2-gbp/ament_package-release/archive/release/eloquent/ament_package/0.8.8-1.tar.gz
    folder: ros-eloquent-ament-package
    fn: ros-eloquent-ament-package.tar.gz

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-ament-cmake
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-export-link-flags
        - ros-eloquent-ament-cmake-export-interfaces
        - ros-eloquent-ament-cmake-export-include-directories
        - ros-eloquent-ament-cmake-libraries
        - ros-eloquent-ament-cmake-export-definitions
        - ros-eloquent-ament-cmake-test
        - ros-eloquent-ament-cmake-export-dependencies
        - ros-eloquent-ament-cmake-version
        - ros-eloquent-ament-cmake-python
        - ros-eloquent-ament-cmake-export-libraries
        - cmake
        - ros-eloquent-ament-cmake-target-dependencies
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-export-link-flags
        - ros-eloquent-ament-cmake-export-interfaces
        - ros-eloquent-ament-cmake-export-include-directories
        - ros-eloquent-ament-cmake-libraries
        - ros-eloquent-ament-cmake-export-definitions
        - ros-eloquent-ament-cmake-test
        - ros-eloquent-ament-cmake-export-dependencies
        - ros-eloquent-ament-cmake-version
        - ros-eloquent-ament-cmake-python
        - ros-eloquent-ament-cmake-export-libraries
        - cmake
        - ros-eloquent-ament-cmake-target-dependencies
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-core
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-package
        - catkin_pkg
        - cmake
      run:
        - python
        - ros-eloquent-ament-package
        - catkin_pkg
        - cmake
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-export-definitions
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-export-dependencies
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-export-include-directories
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-export-interfaces
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-export-libraries
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-export-link-flags
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-include-directories
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-libraries
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-python
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-target-dependencies
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-test
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-cmake-version
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-eloquent-ament-cmake-core
      run:
        - python
        - ros-eloquent-ament-cmake-core
    script: bld_.bat
  - name: ros-eloquent-ament-package
    version: 0.8.8
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - flake8
        - setuptools
        - pytest
      run:
        - python
        - flake8
        - setuptools
        - pytest
    script: bld_.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
