package:
  name: ros
  version: 2020.03.10

source:
  - git_url: https://github.com/ros-gbp/bond_core-release.git
    git_rev: release/noetic/bond/1.8.4-1
    folder: ros-noetic-bond/src/work
  - git_url: https://github.com/ros-gbp/rqt-release.git
    git_rev: release/noetic/rqt_gui_cpp/0.5.1-1
    folder: ros-noetic-rqt-gui-cpp/src/work
  - git_url: https://github.com/ros-gbp/python_qt_binding-release.git
    git_rev: release/noetic/python_qt_binding/0.4.1-1
    folder: ros-noetic-python-qt-binding/src/work
  - git_url: https://github.com/ros-gbp/urdf-release.git
    git_rev: release/noetic/urdf/1.13.2-1
    folder: ros-noetic-urdf/src/work
  - git_url: https://github.com/ros-gbp/urdf-release.git
    git_rev: release/noetic/urdf_parser_plugin/1.13.2-1
    folder: ros-noetic-urdf-parser-plugin/src/work
  - git_url: https://github.com/ros-gbp/rqt-release.git
    git_rev: release/noetic/rqt_gui_py/0.5.1-1
    folder: ros-noetic-rqt-gui-py/src/work
  - git_url: https://github.com/ros-gbp/bond_core-release.git
    git_rev: release/noetic/bondcpp/1.8.4-1
    folder: ros-noetic-bondcpp/src/work
  - git_url: https://github.com/ros-gbp/bond_core-release.git
    git_rev: release/noetic/smclib/1.8.4-1
    folder: ros-noetic-smclib/src/work
  - git_url: https://github.com/ros-gbp/rqt-release.git
    git_rev: release/noetic/rqt_gui/0.5.1-1
    folder: ros-noetic-rqt-gui/src/work
  - git_url: https://github.com/ros-gbp/rqt-release.git
    git_rev: release/noetic/rqt/0.5.1-1
    folder: ros-noetic-rqt/src/work
  - git_url: https://github.com/ros-gbp/qt_gui_core-release.git
    git_rev: release/noetic/qt_gui/0.4.0-1
    folder: ros-noetic-qt-gui/src/work
  - git_url: https://github.com/ros-gbp/qt_gui_core-release.git
    git_rev: release/noetic/qt_gui_cpp/0.4.0-1
    folder: ros-noetic-qt-gui-cpp/src/work
  - git_url: https://github.com/ros-gbp/nodelet_core-release.git
    git_rev: release/noetic/nodelet/1.10.0-1
    folder: ros-noetic-nodelet/src/work
  - git_url: https://github.com/ros-gbp/rosconsole_bridge-release.git
    git_rev: release/noetic/rosconsole_bridge/0.5.4-1
    folder: ros-noetic-rosconsole-bridge/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-bond
    version: 1.8.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-rqt-gui-cpp
    version: 0.5.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - qt
        - ros-noetic-catkin
        - ros-noetic-nodelet
        - ros-noetic-qt-gui
        - ros-noetic-qt-gui-cpp
        - ros-noetic-roscpp
      run:
        - python {{ python }}
        - ros-noetic-nodelet
        - ros-noetic-qt-gui
        - ros-noetic-qt-gui-cpp
        - ros-noetic-roscpp
    script: bld_catkin.bat
  - name: ros-noetic-python-qt-binding
    version: 0.4.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - pyqt
        - python {{ python }}
        - qt
        - ros-noetic-catkin
        - ros-noetic-rosbuild
      run:
        - pyqt
        - python {{ python }}
        - ros-noetic-catkin
    script: bld_catkin.bat
  - name: ros-noetic-urdf
    version: 1.13.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cmake-modules
        - ros-noetic-pluginlib
        - ros-noetic-rosconsole-bridge
        - ros-noetic-roscpp
        - ros-noetic-rostest
        - ros-noetic-urdf-parser-plugin
        - tinyxml
        - tinyxml2
        - urdfdom
        - urdfdom_headers
      run:
        - python {{ python }}
        - ros-noetic-pluginlib
        - ros-noetic-rosconsole-bridge
        - ros-noetic-roscpp
        - tinyxml
        - tinyxml2
        - urdfdom
        - urdfdom_headers
    script: bld_catkin.bat
  - name: ros-noetic-urdf-parser-plugin
    version: 1.13.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - urdfdom_headers
      run:
        - python {{ python }}
        - urdfdom_headers
    script: bld_catkin.bat
  - name: ros-noetic-rqt-gui-py
    version: 0.5.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-qt-gui
        - ros-noetic-rospy
        - ros-noetic-rqt-gui
      run:
        - python {{ python }}
        - ros-noetic-qt-gui
        - ros-noetic-rospy
        - ros-noetic-rqt-gui
    script: bld_catkin.bat
  - name: ros-noetic-bondcpp
    version: 1.8.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - python {{ python }}
        - ros-noetic-bond
        - ros-noetic-catkin
        - ros-noetic-cmake-modules
        - ros-noetic-roscpp
        - ros-noetic-smclib
      run:
        - boost
        - python {{ python }}
        - ros-noetic-bond
        - ros-noetic-roscpp
        - ros-noetic-smclib
    script: bld_catkin.bat
  - name: ros-noetic-smclib
    version: 1.8.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - python {{ python }}
    script: bld_catkin.bat
  - name: ros-noetic-rqt-gui
    version: 0.5.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-qt-gui
      run:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-qt-gui
    script: bld_catkin.bat
  - name: ros-noetic-rqt
    version: 0.5.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-rqt-gui
        - ros-noetic-rqt-gui-cpp
        - ros-noetic-rqt-gui-py
      run:
        - python {{ python }}
        - ros-noetic-rqt-gui
        - ros-noetic-rqt-gui-cpp
        - ros-noetic-rqt-gui-py
    script: bld_catkin.bat
  - name: ros-noetic-qt-gui
    version: 0.4.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - pyqt
        - python {{ python }}
        - qt
        - ros-noetic-catkin
      run:
        - python {{ python }}
        - ros-noetic-python-qt-binding
        - rospkg
    script: bld_catkin.bat
  - name: ros-noetic-qt-gui-cpp
    version: 0.4.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - pkg-config
        - python {{ python }}
        - qt
        - ros-noetic-catkin
        - ros-noetic-cmake-modules
        - ros-noetic-pluginlib
        - ros-noetic-python-qt-binding
        - ros-noetic-qt-gui
        - tinyxml
      run:
        - python {{ python }}
        - ros-noetic-pluginlib
        - ros-noetic-qt-gui
        - tinyxml
    script: bld_catkin.bat
  - name: ros-noetic-nodelet
    version: 1.10.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - python {{ python }}
        - ros-noetic-bondcpp
        - ros-noetic-catkin
        - ros-noetic-cmake-modules
        - ros-noetic-message-generation
        - ros-noetic-pluginlib
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-std-msgs
      run:
        - boost
        - python {{ python }}
        - ros-noetic-bondcpp
        - ros-noetic-message-runtime
        - ros-noetic-pluginlib
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-rospy
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-rosconsole-bridge
    version: 0.5.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - console_bridge
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cpp-common
        - ros-noetic-rosconsole
      run:
        - console_bridge
        - python {{ python }}
        - ros-noetic-cpp-common
        - ros-noetic-rosconsole
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
