package:
  name: ros
  version: 2020.02.28

source:
  - git_url: https://github.com/ros2-gbp/vision_opencv-release.git
    git_rev: release/eloquent/cv_bridge/2.1.4-1
    folder: ros-eloquent-cv-bridge/src/work
  - git_url: https://github.com/ros2-gbp/image_common-release.git
    git_rev: release/eloquent/image_transport/2.2.1-1
    folder: ros-eloquent-image-transport/src/work
  - git_url: https://github.com/ros2-gbp/python_qt_binding-release.git
    git_rev: release/eloquent/python_qt_binding/1.0.3-1
    folder: ros-eloquent-python-qt-binding/src/work
  - git_url: https://github.com/ros2-gbp/qt_gui_core-release.git
    git_rev: release/eloquent/qt_dotgraph/1.0.7-1
    folder: ros-eloquent-qt-dotgraph/src/work
  - git_url: https://github.com/ros2-gbp/qt_gui_core-release.git
    git_rev: release/eloquent/qt_gui/1.0.7-1
    folder: ros-eloquent-qt-gui/src/work
  - git_url: https://github.com/ros2-gbp/qt_gui_core-release.git
    git_rev: release/eloquent/qt_gui_cpp/1.0.7-1
    folder: ros-eloquent-qt-gui-cpp/src/work
  - git_url: https://github.com/ros2-gbp/qt_gui_core-release.git
    git_rev: release/eloquent/qt_gui_py_common/1.0.7-1
    folder: ros-eloquent-qt-gui-py-common/src/work
  - git_url: https://github.com/ros2-gbp/rqt_action-release.git
    git_rev: release/eloquent/rqt_action/1.0.1-1
    folder: ros-eloquent-rqt-action/src/work
  - git_url: https://github.com/ros2-gbp/rqt_common_plugins-release.git
    git_rev: release/eloquent/rqt_common_plugins/1.0.0-1
    folder: ros-eloquent-rqt-common-plugins/src/work
  - git_url: https://github.com/ros2-gbp/rqt_console-release.git
    git_rev: release/eloquent/rqt_console/1.1.1-1
    folder: ros-eloquent-rqt-console/src/work
  - git_url: https://github.com/ros2-gbp/rqt_graph-release.git
    git_rev: release/eloquent/rqt_graph/1.0.4-1
    folder: ros-eloquent-rqt-graph/src/work
  - git_url: https://github.com/ros2-gbp/rqt-release.git
    git_rev: release/eloquent/rqt_gui/1.0.5-1
    folder: ros-eloquent-rqt-gui/src/work
  - git_url: https://github.com/ros2-gbp/rqt-release.git
    git_rev: release/eloquent/rqt_gui_cpp/1.0.5-1
    folder: ros-eloquent-rqt-gui-cpp/src/work
  - git_url: https://github.com/ros2-gbp/rqt-release.git
    git_rev: release/eloquent/rqt_gui_py/1.0.5-1
    folder: ros-eloquent-rqt-gui-py/src/work
  - git_url: https://github.com/ros2-gbp/rqt_image_view-release.git
    git_rev: release/eloquent/rqt_image_view/1.0.4-1
    folder: ros-eloquent-rqt-image-view/src/work
  - git_url: https://github.com/ros2-gbp/rqt_msg-release.git
    git_rev: release/eloquent/rqt_msg/1.0.2-1
    folder: ros-eloquent-rqt-msg/src/work
  - git_url: https://github.com/ros2-gbp/rqt_plot-release.git
    git_rev: release/eloquent/rqt_plot/1.0.7-1
    folder: ros-eloquent-rqt-plot/src/work
  - git_url: https://github.com/ros2-gbp/rqt_publisher-release.git
    git_rev: release/eloquent/rqt_publisher/1.1.0-1
    folder: ros-eloquent-rqt-publisher/src/work
  - git_url: https://github.com/ros2-gbp/rqt-release.git
    git_rev: release/eloquent/rqt_py_common/1.0.5-1
    folder: ros-eloquent-rqt-py-common/src/work
  - git_url: https://github.com/ros2-gbp/rqt_py_console-release.git
    git_rev: release/eloquent/rqt_py_console/1.0.0-1
    folder: ros-eloquent-rqt-py-console/src/work
  - git_url: https://github.com/ros2-gbp/rqt_reconfigure-release.git
    git_rev: release/eloquent/rqt_reconfigure/1.0.4-1
    folder: ros-eloquent-rqt-reconfigure/src/work
  - git_url: https://github.com/ros2-gbp/rqt_service_caller-release.git
    git_rev: release/eloquent/rqt_service_caller/1.0.3-1
    folder: ros-eloquent-rqt-service-caller/src/work
  - git_url: https://github.com/ros2-gbp/rqt_shell-release.git
    git_rev: release/eloquent/rqt_shell/1.0.0-1
    folder: ros-eloquent-rqt-shell/src/work
  - git_url: https://github.com/ros2-gbp/rqt_srv-release.git
    git_rev: release/eloquent/rqt_srv/1.0.1-1
    folder: ros-eloquent-rqt-srv/src/work
  - git_url: https://github.com/ros2-gbp/rqt_top-release.git
    git_rev: release/eloquent/rqt_top/1.0.0-1
    folder: ros-eloquent-rqt-top/src/work
  - git_url: https://github.com/ros2-gbp/rqt_topic-release.git
    git_rev: release/eloquent/rqt_topic/1.1.0-1
    folder: ros-eloquent-rqt-topic/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-cv-bridge
    version: 2.1.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-sensor-msgs
        - ros-eloquent-python-cmake-module
        - opencv 3.*
        - numpy
        - ros-eloquent-ament-cmake-ros
        - boost
      run:
        - python {{ python }}
        - ros-eloquent-ament-index-python
        - ros-eloquent-sensor-msgs
        - opencv 3.*
        - numpy
        - boost
    script: bld_colcon.bat
  - name: ros-eloquent-image-transport
    version: 2.2.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-sensor-msgs
        - ros-eloquent-rclcpp
        - ros-eloquent-pluginlib
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-message-filters
      run:
        - python {{ python }}
        - ros-eloquent-sensor-msgs
        - ros-eloquent-rclcpp
        - ros-eloquent-pluginlib
        - ros-eloquent-message-filters
    script: bld_colcon.bat
  - name: ros-eloquent-python-qt-binding
    version: 1.0.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
        - qt
        - pyqt
      run:
        - python {{ python }}
        - pyqt
    script: bld_colcon.bat
  - name: ros-eloquent-qt-dotgraph
    version: 1.0.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-python-qt-binding
        - python {{ python }}
        - pydot
    script: bld_colcon.bat
  - name: ros-eloquent-qt-gui
    version: 1.0.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
        - qt
        - pyqt
      run:
        - ros-eloquent-python-qt-binding
        - python {{ python }}
        - ros-eloquent-ament-index-python
        - catkin_pkg
    script: bld_colcon.bat
  - name: ros-eloquent-qt-gui-cpp
    version: 1.0.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - pkg-config
        - ros-eloquent-python-qt-binding
        - ros-eloquent-tinyxml2-vendor
        - ros-eloquent-ament-cmake
        - ros-eloquent-pluginlib
        - qt
      run:
        - python {{ python }}
        - ros-eloquent-tinyxml2-vendor
        - ros-eloquent-qt-gui
        - ros-eloquent-pluginlib
    script: bld_colcon.bat
  - name: ros-eloquent-qt-gui-py-common
    version: 1.0.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-python-qt-binding
        - python {{ python }}
        - ros-eloquent-ament-index-python
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-action
    version: 1.0.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rclpy
        - ros-eloquent-rqt-gui-py
        - ros-eloquent-rqt-msg
        - ros-eloquent-rqt-py-common
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-common-plugins
    version: 1.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - python {{ python }}
        - ros-eloquent-rqt-publisher
        - ros-eloquent-rqt-console
        - ros-eloquent-rqt-action
        - ros-eloquent-rqt-top
        - ros-eloquent-rqt-reconfigure
        - ros-eloquent-rqt-image-view
        - ros-eloquent-rqt-srv
        - ros-eloquent-rqt-plot
        - ros-eloquent-rqt-shell
        - ros-eloquent-rqt-msg
        - ros-eloquent-rqt-topic
        - ros-eloquent-rqt-service-caller
        - ros-eloquent-rqt-graph
        - ros-eloquent-rqt-py-console
        - ros-eloquent-rqt-py-common
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-console
    version: 1.1.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rclpy
        - ros-eloquent-ament-index-python
        - ros-eloquent-rqt-gui-py
        - ros-eloquent-rcl-interfaces
        - ros-eloquent-rqt-py-common
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-graph
    version: 1.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-qt-dotgraph
        - ros-eloquent-python-qt-binding
        - ros-eloquent-ament-index-python
        - ros-eloquent-rqt-gui-py
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-gui
    version: 1.0.5
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-qt-gui
      run:
        - python {{ python }}
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rclpy
        - ros-eloquent-ament-index-python
        - ros-eloquent-qt-gui
        - catkin_pkg
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-gui-cpp
    version: 1.0.5
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-qt-gui
        - ros-eloquent-ament-cmake
        - ros-eloquent-rclcpp
        - qt
        - ros-eloquent-qt-gui-cpp
      run:
        - python {{ python }}
        - ros-eloquent-rclcpp
        - ros-eloquent-qt-gui
        - ros-eloquent-qt-gui-cpp
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-gui-py
    version: 1.0.5
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-qt-gui
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-qt-gui
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-image-view
    version: 1.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-qt-gui-cpp
        - ros-eloquent-sensor-msgs
        - ros-eloquent-ament-cmake
        - ros-eloquent-rclcpp
        - ros-eloquent-cv-bridge
        - qt
        - ros-eloquent-geometry-msgs
        - ros-eloquent-rqt-gui-cpp
        - ros-eloquent-image-transport
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-qt-gui-cpp
        - ros-eloquent-sensor-msgs
        - ros-eloquent-rclcpp
        - ros-eloquent-cv-bridge
        - ros-eloquent-geometry-msgs
        - ros-eloquent-rqt-gui-cpp
        - ros-eloquent-image-transport
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-msg
    version: 1.0.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-rqt-console
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rclpy
        - ros-eloquent-rqt-gui-py
        - catkin_pkg
        - ros-eloquent-rqt-py-common
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-plot
    version: 1.0.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-qt-gui-py-common
        - ros-eloquent-std-msgs
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rclpy
        - matplotlib
        - numpy
        - ros-eloquent-rqt-gui-py
        - catkin_pkg
        - ros-eloquent-rqt-py-common
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-publisher
    version: 1.1.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-qt-gui-py-common
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rqt-gui-py
        - catkin_pkg
        - ros-eloquent-rqt-py-common
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-py-common
    version: 1.0.5
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-rclpy
        - ros-eloquent-ament-cmake
        - qt
        - ros-eloquent-rosidl-default-generators
      run:
        - python {{ python }}
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rclpy
        - ros-eloquent-qt-gui
        - ros-eloquent-rosidl-default-runtime
        - qt
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-py-console
    version: 1.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-qt-gui-py-common
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rclpy
        - ros-eloquent-ament-index-python
        - ros-eloquent-qt-gui
        - ros-eloquent-rqt-gui-py
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-reconfigure
    version: 1.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-qt-gui-py-common
        - ros-eloquent-rqt-console
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rclpy
        - ros-eloquent-ament-index-python
        - ros-eloquent-rqt-gui-py
        - pyyaml
        - ros-eloquent-rqt-py-common
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-service-caller
    version: 1.0.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-rqt-gui-py
        - ros-eloquent-rqt-py-common
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-shell
    version: 1.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-qt-gui-py-common
        - ros-eloquent-python-qt-binding
        - ros-eloquent-qt-gui
        - ros-eloquent-rqt-gui-py
        - catkin_pkg
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-srv
    version: 1.0.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-rclpy
        - ros-eloquent-rqt-gui-py
        - ros-eloquent-rqt-msg
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-top
    version: 1.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rclpy
        - psutil
        - ros-eloquent-rqt-gui-py
    script: bld_colcon.bat
  - name: ros-eloquent-rqt-topic
    version: 1.1.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
      run:
        - ros-eloquent-rqt-gui
        - python {{ python }}
        - ros-eloquent-python-qt-binding
        - ros-eloquent-rqt-gui-py
        - ros-eloquent-rqt-py-common
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
