package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/rmw_fastrtps-release.git
    git_rev: release/eloquent/rmw_fastrtps_dynamic_cpp/0.8.1-1
    folder: ros-eloquent-rmw-fastrtps-dynamic-cpp/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-rmw-fastrtps-dynamic-cpp
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-fastrtps
        - ros-eloquent-fastcdr
        - ros-eloquent-rosidl-typesupport-introspection-cpp
        - ros-eloquent-rosidl-generator-c
        - ros-eloquent-rmw
        - ros-eloquent-rosidl-typesupport-introspection-c
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-rcpputils
        - ros-eloquent-rcutils
        - ros-eloquent-ament-cmake
        - ros-eloquent-rmw-fastrtps-shared-cpp
        - ros-eloquent-rosidl-typesupport-fastrtps-cpp
        - ros-eloquent-rosidl-typesupport-fastrtps-c
        - ros-eloquent-fastrtps-cmake-module
      run:
        - python
        - ros-eloquent-fastrtps
        - ros-eloquent-fastcdr
        - ros-eloquent-rosidl-typesupport-introspection-cpp
        - ros-eloquent-rosidl-generator-c
        - ros-eloquent-rmw
        - ros-eloquent-rosidl-typesupport-introspection-c
        - ros-eloquent-rcpputils
        - ros-eloquent-rcutils
        - ros-eloquent-ament-cmake
        - ros-eloquent-rmw-fastrtps-shared-cpp
        - ros-eloquent-rosidl-typesupport-fastrtps-cpp
        - ros-eloquent-rosidl-typesupport-fastrtps-c
        - ros-eloquent-fastrtps-cmake-module
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
