package:
  name: ros
  version: 2020.03.08

source:
  - git_url: https://github.com/ros-gbp/catkin-release.git
    git_rev: release/noetic/catkin/0.8.1-1
    folder: ros-noetic-catkin/src/work

build:
  number: 3
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-catkin
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - catkin_pkg
        - cmake
        - empy
        - gmock
        - gtest
        - mock
        - nose
        - python {{ python }}
        - setuptools
      run:
        - catkin_pkg
        - cmake
        - empy
        - gmock
        - gtest
        - nose
        - python {{ python }}
        - setuptools
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
