package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/ament_index-release.git
    git_rev: release/eloquent/ament_index_cpp/0.7.2-1
    folder: ros-eloquent-ament-index-cpp/src/work
  - git_url: https://github.com/ros2-gbp/class_loader-release.git
    git_rev: release/eloquent/class_loader/1.4.1-1
    folder: ros-eloquent-class-loader/src/work
  - git_url: https://github.com/ros2-gbp/console_bridge_vendor-release.git
    git_rev: release/eloquent/console_bridge_vendor/1.2.0-1
    folder: ros-eloquent-console-bridge-vendor/src/work
  - git_url: https://github.com/ros2-gbp/pluginlib-release.git
    git_rev: release/eloquent/pluginlib/2.4.1-1
    folder: ros-eloquent-pluginlib/src/work
  - git_url: https://github.com/ros2-gbp/tinyxml2_vendor-release.git
    git_rev: release/eloquent/tinyxml2_vendor/0.6.1-1
    folder: ros-eloquent-tinyxml2-vendor/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-ament-index-cpp
    version: 0.7.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - python
    script: bld_colcon.bat
  - name: ros-eloquent-class-loader
    version: 1.4.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
        - poco
        - ros-eloquent-console-bridge-vendor
        - console_bridge
        - ros-eloquent-poco-vendor
      run:
        - python
        - poco
        - console_bridge
        - ros-eloquent-poco-vendor
        - ros-eloquent-console-bridge-vendor
    script: bld_colcon.bat
  - name: ros-eloquent-console-bridge-vendor
    version: 1.2.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - console_bridge
        - ros-eloquent-ament-cmake
      run:
        - python
        - console_bridge
    script: bld_colcon.bat
  - name: ros-eloquent-pluginlib
    version: 2.4.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-class-loader
        - ros-eloquent-ament-index-cpp
        - ros-eloquent-ament-cmake
        - ros-eloquent-tinyxml2-vendor
        - ros-eloquent-rcutils
      run:
        - python
        - ros-eloquent-class-loader
        - ros-eloquent-ament-index-cpp
        - ros-eloquent-tinyxml2-vendor
        - ros-eloquent-rcutils
    script: bld_colcon.bat
  - name: ros-eloquent-tinyxml2-vendor
    version: 0.6.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - tinyxml2
        - cmake
      run:
        - python
        - tinyxml2
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
