package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/rcl_interfaces-release.git
    git_rev: release/eloquent/action_msgs/0.8.0-1
    folder: ros-eloquent-action-msgs/src/work
  - git_url: https://github.com/ros2-gbp/rcl-release.git
    git_rev: release/eloquent/rcl_action/0.8.4-1
    folder: ros-eloquent-rcl-action/src/work
  - git_url: https://github.com/ros2-gbp/rclpy-release.git
    git_rev: release/eloquent/rclpy/0.8.4-1
    folder: ros-eloquent-rclpy/src/work
  - git_url: https://github.com/ros2-gbp/ros2cli-release.git
    git_rev: release/eloquent/ros2cli/0.8.7-1
    folder: ros-eloquent-ros2cli/src/work
  - git_url: https://github.com/ros2-gbp/rcl_interfaces-release.git
    git_rev: release/eloquent/rosgraph_msgs/0.8.0-1
    folder: ros-eloquent-rosgraph-msgs/src/work
  - git_url: https://github.com/ros2-gbp/unique_identifier_msgs-release.git
    git_rev: release/eloquent/unique_identifier_msgs/2.1.0-1
    folder: ros-eloquent-unique-identifier-msgs/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-action-msgs
    version: 0.8.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-unique-identifier-msgs
      run:
        - python
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-rosidl-default-runtime
        - ros-eloquent-unique-identifier-msgs
    script: bld_colcon.bat
  - name: ros-eloquent-rclpy
    version: 0.8.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-rcutils
        - ros-eloquent-python-cmake-module
        - ros-eloquent-rcl
        - ros-eloquent-rcl-action
        - ros-eloquent-rcl-yaml-param-parser
        - ros-eloquent-rmw-implementation-cmake
        - ros-eloquent-ament-cmake
        - ros-eloquent-rmw-implementation
        - ros-eloquent-unique-identifier-msgs
      run:
        - python
        - ros-eloquent-rosgraph-msgs
        - ros-eloquent-rcl
        - ros-eloquent-rcl-action
        - ros-eloquent-rcl-yaml-param-parser
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-ament-index-python
        - ros-eloquent-rmw-implementation
        - ros-eloquent-rcl-interfaces
        - ros-eloquent-unique-identifier-msgs
    script: bld_colcon.bat
  - name: ros-eloquent-rcl-action
    version: 0.8.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-rcutils
        - ros-eloquent-rcl
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-action-msgs
        - ros-eloquent-rosidl-generator-c
        - ros-eloquent-rmw
      run:
        - python
        - ros-eloquent-rcutils
        - ros-eloquent-rcl
        - ros-eloquent-action-msgs
        - ros-eloquent-rosidl-generator-c
        - ros-eloquent-rmw
    script: bld_colcon.bat
  - name: ros-eloquent-ros2cli
    version: 0.8.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
      run:
        - python
        - netifaces
        - ros-eloquent-rclpy
    script: bld_colcon.bat
  - name: ros-eloquent-rosgraph-msgs
    version: 0.8.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-ament-cmake
      run:
        - python
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-rosidl-default-runtime
    script: bld_colcon.bat
  - name: ros-eloquent-unique-identifier-msgs
    version: 2.1.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-ament-cmake
      run:
        - python
        - ros-eloquent-rosidl-default-runtime
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
