package:
  name: ros
  version: 2020.03.09

source:
  - git_url: https://github.com/ros-gbp/ros-release.git
    git_rev: release/noetic/rosclean/1.15.0-1
    folder: ros-noetic-rosclean/src/work
  - git_url: https://github.com/ros-gbp/ros_tutorials-release.git
    git_rev: release/noetic/roscpp_tutorials/0.9.2-1
    folder: ros-noetic-roscpp-tutorials/src/work
  - git_url: https://github.com/ros-gbp/ros_comm-release.git
    git_rev: release/noetic/roslaunch/1.15.3-1
    folder: ros-noetic-roslaunch/src/work
  - git_url: https://github.com/ros-gbp/ros_comm-release.git
    git_rev: release/noetic/rosmaster/1.15.3-1
    folder: ros-noetic-rosmaster/src/work
  - git_url: https://github.com/ros-gbp/ros_comm-release.git
    git_rev: release/noetic/rosout/1.15.3-1
    folder: ros-noetic-rosout/src/work
  - git_url: https://github.com/ros-gbp/ros_comm-release.git
    git_rev: release/noetic/rosparam/1.15.3-1
    folder: ros-noetic-rosparam/src/work
  - git_url: https://github.com/ros-gbp/ros_tutorials-release.git
    git_rev: release/noetic/rospy_tutorials/0.9.2-1
    folder: ros-noetic-rospy-tutorials/src/work
  - git_url: https://github.com/ros-gbp/ros_comm-release.git
    git_rev: release/noetic/rostest/1.15.3-1
    folder: ros-noetic-rostest/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-rosclean
    version: 1.15.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - setuptools
      run:
        - python {{ python }}
        - rospkg
    script: bld_catkin.bat
  - name: ros-noetic-roscpp-tutorials
    version: 0.9.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-roscpp-serialization
        - ros-noetic-rostime
        - ros-noetic-std-msgs
      run:
        - boost
        - python {{ python }}
        - ros-noetic-message-runtime
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-roscpp-serialization
        - ros-noetic-rostime
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-roslaunch
    version: 1.15.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-rosbuild
      run:
        - paramiko
        - python {{ python }}
        - pyyaml
        - ros-noetic-rosclean
        - ros-noetic-rosgraph-msgs
        - ros-noetic-roslib
        - ros-noetic-rosmaster
        - ros-noetic-rosout
        - ros-noetic-rosparam
        - ros-noetic-rosunit
        - rospkg
    script: bld_catkin.bat
  - name: ros-noetic-rosmaster
    version: 1.15.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - defusedxml
        - python {{ python }}
        - ros-noetic-rosgraph
    script: bld_catkin.bat
  - name: ros-noetic-rosout
    version: 1.15.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-roscpp
        - ros-noetic-rosgraph-msgs
      run:
        - python {{ python }}
        - ros-noetic-roscpp
        - ros-noetic-rosgraph-msgs
    script: bld_catkin.bat
  - name: ros-noetic-rosparam
    version: 1.15.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - python {{ python }}
        - pyyaml
        - ros-noetic-rosgraph
    script: bld_catkin.bat
  - name: ros-noetic-rospy-tutorials
    version: 0.9.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-roscpp-tutorials
        - ros-noetic-rospy
        - ros-noetic-rostest
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-message-runtime
        - ros-noetic-rospy
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-rostest
    version: 1.15.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-rosgraph
        - ros-noetic-roslaunch
        - ros-noetic-rosmaster
        - ros-noetic-rospy
        - ros-noetic-rosunit
      run:
        - boost
        - python {{ python }}
        - ros-noetic-rosgraph
        - ros-noetic-roslaunch
        - ros-noetic-rosmaster
        - ros-noetic-rospy
        - ros-noetic-rosunit
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
