package:
  name: ros
  version: 2020.03.03

source:
  - git_url: https://github.com/ros2-dotnet/dotnet_cmake_module.git
    git_rev: master
    folder: ros-eloquent-dotnet-cmake-module/src/work
  - git_url: https://github.com/ros2-dotnet/ros2_dotnet.git
    git_rev: master
    folder: ros-eloquent-rcldotnet/src/work
  - git_url: https://github.com/ros2-dotnet/ros2_dotnet.git
    git_rev: master
    folder: ros-eloquent-rcldotnet-common/src/work
  - git_url: https://github.com/ros2-dotnet/ros2_dotnet.git
    git_rev: master
    folder: ros-eloquent-rcldotnet-examples/src/work
  - git_url: https://github.com/ros2-dotnet/ros2_dotnet.git
    git_rev: master
    folder: ros-eloquent-rosidl-generator-dotnet/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-dotnet-cmake-module
    version: 0.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-lint-common
        - ros-eloquent-ament-cmake
        - ros-eloquent-ament-lint-auto
        - python {{ python }}
      run:
        - python {{ python }}
    script: bld_colcon.bat
  - name: ros-eloquent-rcldotnet
    version: 0.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-dotnet-cmake-module
        - colcon-common-extensions
        - ros-eloquent-ament-cmake-export-assemblies
        - ros-eloquent-rcldotnet-common
        - ros-eloquent-ament-cmake
        - ros-eloquent-rmw-implementation-cmake
        - ros-eloquent-rcl
        - ros-eloquent-rmw
        - ros-eloquent-rosidl-cmake
        - python {{ python }}
      run:
        - ros-eloquent-rmw-implementation
        - ros-eloquent-rosidl-generator-c
        - ros-eloquent-rosidl-parser
        - ros-eloquent-rmw-implementation-cmake
        - ros-eloquent-rcl
        - ros-eloquent-rosidl-cmake
        - python {{ python }}
    script: bld_colcon.bat
  - name: ros-eloquent-rcldotnet-common
    version: 0.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-dotnet-cmake-module
        - colcon-common-extensions
        - ros-eloquent-ament-cmake-export-assemblies
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-cmake
        - python {{ python }}
      run:
        - ros-eloquent-rosidl-cmake
        - python {{ python }}
    script: bld_colcon.bat
  - name: ros-eloquent-rcldotnet-examples
    version: 0.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-std-msgs
        - ros-eloquent-rcldotnet
        - ros-eloquent-dotnet-cmake-module
        - colcon-common-extensions
        - ros-eloquent-ament-cmake-export-assemblies
        - ros-eloquent-sensor-msgs
        - ros-eloquent-rcldotnet-common
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-cmake
        - python {{ python }}
        - ros-eloquent-example-interfaces
      run:
        - ros-eloquent-std-msgs
        - ros-eloquent-rcldotnet
        - ros-eloquent-sensor-msgs
        - ros-eloquent-rcldotnet-common
        - ros-eloquent-rosidl-cmake
        - python {{ python }}
        - ros-eloquent-example-interfaces
    script: bld_colcon.bat
  - name: ros-eloquent-rosidl-generator-dotnet
    version: 0.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-dotnet-cmake-module
        - ros-eloquent-rosidl-generator-c
        - colcon-common-extensions
        - ros-eloquent-ament-cmake-export-assemblies
        - ros-eloquent-rcldotnet-common
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-cmake
        - python {{ python }}
      run:
        - ros-eloquent-rmw-implementation
        - ros-eloquent-dotnet-cmake-module
        - ros-eloquent-rosidl-generator-c
        - ros-eloquent-ament-cmake-export-assemblies
        - ros-eloquent-rosidl-parser
        - ros-eloquent-rcldotnet-common
        - ros-eloquent-ament-cmake
        - ros-eloquent-rmw-implementation-cmake
        - ros-eloquent-rosidl-cmake
        - python {{ python }}
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
