package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/poco_vendor-release.git
    git_rev: release/eloquent/poco_vendor/1.2.0-1
    folder: ros-eloquent-poco-vendor/src/work
  - git_url: https://github.com/ros2-gbp/rcpputils-release.git
    git_rev: release/eloquent/rcpputils/0.2.1-1
    folder: ros-eloquent-rcpputils/src/work
  - git_url: https://github.com/ros2-gbp/rmw_fastrtps-release.git
    git_rev: release/eloquent/rmw_fastrtps_cpp/0.8.1-1
    folder: ros-eloquent-rmw-fastrtps-cpp/src/work
  - git_url: https://github.com/ros2-gbp/rmw_fastrtps-release.git
    git_rev: release/eloquent/rmw_fastrtps_shared_cpp/0.8.1-1
    folder: ros-eloquent-rmw-fastrtps-shared-cpp/src/work
  - git_url: https://github.com/ros2-gbp/rmw_implementation-release.git
    git_rev: release/eloquent/rmw_implementation/0.8.2-2
    folder: ros-eloquent-rmw-implementation/src/work
  - git_url: https://github.com/ros2-gbp/rmw-release.git
    git_rev: release/eloquent/rmw_implementation_cmake/0.8.1-1
    folder: ros-eloquent-rmw-implementation-cmake/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-poco-vendor
    version: 1.2.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - poco
        - cmake
        - pcre
        - zlib
      run:
        - python
        - poco
        - cmake
        - pcre
        - zlib
    script: bld_colcon.bat
  - name: ros-eloquent-rcpputils
    version: 0.2.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-rcutils
        - ros-eloquent-ament-cmake
      run:
        - python
    script: bld_colcon.bat
  - name: ros-eloquent-rmw-fastrtps-cpp
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-fastcdr
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-rosidl-cmake
        - ros-eloquent-rosidl-generator-c
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-generator-cpp
        - ros-eloquent-fastrtps
        - ros-eloquent-rmw-fastrtps-shared-cpp
        - ros-eloquent-rcutils
        - ros-eloquent-rosidl-typesupport-fastrtps-c
        - ros-eloquent-rosidl-typesupport-fastrtps-cpp
        - ros-eloquent-fastrtps-cmake-module
        - ros-eloquent-rmw
      run:
        - python
        - ros-eloquent-rosidl-cmake
        - ros-eloquent-rmw
        - ros-eloquent-rosidl-generator-c
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-generator-cpp
        - ros-eloquent-fastrtps
        - ros-eloquent-rmw-fastrtps-shared-cpp
        - ros-eloquent-rcutils
        - ros-eloquent-rosidl-typesupport-fastrtps-c
        - ros-eloquent-rosidl-typesupport-fastrtps-cpp
        - ros-eloquent-fastrtps-cmake-module
        - ros-eloquent-fastcdr
    script: bld_colcon.bat
  - name: ros-eloquent-rmw-fastrtps-shared-cpp
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-rmw
        - ros-eloquent-ament-cmake
        - ros-eloquent-rcpputils
        - ros-eloquent-fastrtps
        - ros-eloquent-rcutils
        - ros-eloquent-fastrtps-cmake-module
        - ros-eloquent-fastcdr
      run:
        - python
        - ros-eloquent-rmw
        - ros-eloquent-ament-cmake
        - ros-eloquent-rcpputils
        - ros-eloquent-fastrtps
        - ros-eloquent-rcutils
        - ros-eloquent-fastrtps-cmake-module
        - ros-eloquent-fastcdr
    script: bld_colcon.bat
  - name: ros-eloquent-rmw-implementation
    version: 0.8.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - poco
        - ros-eloquent-ament-cmake
        - ros-eloquent-ament-cmake-python
        - ros-eloquent-poco-vendor
        - ros-eloquent-rmw-implementation-cmake
        - ros-eloquent-rcutils
        - ros-eloquent-rmw-fastrtps-cpp
        - ros-eloquent-rmw
      run:
        - python
        - poco
        - ros-eloquent-ament-index-python
        - ros-eloquent-rmw-implementation-cmake
        - ros-eloquent-poco-vendor
    script: bld_colcon.bat
  - name: ros-eloquent-rmw-implementation-cmake
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - python
        - ros-eloquent-ament-cmake
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
