package:
  name: ros
  version: 2020.02.28

source:
  - git_url: https://github.com/ros2-gbp/perception_pcl-release.git
    git_rev: release/eloquent/pcl_conversions/2.1.0-1
    folder: ros-eloquent-pcl-conversions/src/work
  - git_url: https://github.com/ros2-gbp/pcl_msgs-release.git
    git_rev: release/eloquent/pcl_msgs/1.0.0-1
    folder: ros-eloquent-pcl-msgs/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-pcl-conversions
    version: 2.1.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-pcl-msgs
        - eigen
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-std-msgs
        - ros-eloquent-sensor-msgs
        - ros-eloquent-ament-cmake
        - ros-eloquent-message-filters
        - ros-eloquent-rclcpp
        - pcl
      run:
        - ros-eloquent-pcl-msgs
        - eigen
        - python {{ python }}
        - ros-eloquent-std-msgs
        - ros-eloquent-sensor-msgs
        - ros-eloquent-message-filters
        - ros-eloquent-rclcpp
        - pcl
    script: bld_colcon.bat
  - name: ros-eloquent-pcl-msgs
    version: 1.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-std-msgs
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-sensor-msgs
        - ros-eloquent-ament-cmake
      run:
        - python {{ python }}
        - ros-eloquent-rosidl-default-runtime
        - ros-eloquent-std-msgs
        - ros-eloquent-sensor-msgs
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
