package:
  name: ros
  version: 2020.03.11

source:
  - git_url: https://github.com/ros-gbp/python_qt_binding-release.git
    git_rev: release/noetic/python_qt_binding/0.4.1-1
    folder: ros-noetic-python-qt-binding/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-python-qt-binding
    version: 0.4.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - pyqt
        - python {{ python }}
        - qt
        - ros-noetic-catkin
        - ros-noetic-rosbuild
      run:
        - pyqt
        - python {{ python }}
        - ros-noetic-catkin
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
