package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/actionlib_msgs/0.8.1-1
    folder: ros-eloquent-actionlib-msgs/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/common_interfaces/0.8.1-1
    folder: ros-eloquent-common-interfaces/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/diagnostic_msgs/0.8.1-1
    folder: ros-eloquent-diagnostic-msgs/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/geometry_msgs/0.8.1-1
    folder: ros-eloquent-geometry-msgs/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/nav_msgs/0.8.1-1
    folder: ros-eloquent-nav-msgs/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/sensor_msgs/0.8.1-1
    folder: ros-eloquent-sensor-msgs/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/shape_msgs/0.8.1-1
    folder: ros-eloquent-shape-msgs/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/std_msgs/0.8.1-1
    folder: ros-eloquent-std-msgs/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/std_srvs/0.8.1-1
    folder: ros-eloquent-std-srvs/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/stereo_msgs/0.8.1-1
    folder: ros-eloquent-stereo-msgs/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/trajectory_msgs/0.8.1-1
    folder: ros-eloquent-trajectory-msgs/src/work
  - git_url: https://github.com/ros2-gbp/common_interfaces-release.git
    git_rev: release/eloquent/visualization_msgs/0.8.1-1
    folder: ros-eloquent-visualization-msgs/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-actionlib-msgs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-default-generators
      run:
        - python
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-rosidl-default-runtime
    script: bld_colcon.bat
  - name: ros-eloquent-common-interfaces
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - python
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-sensor-msgs
        - ros-eloquent-trajectory-msgs
        - ros-eloquent-nav-msgs
        - ros-eloquent-std-msgs
        - ros-eloquent-std-srvs
        - ros-eloquent-diagnostic-msgs
        - ros-eloquent-visualization-msgs
        - ros-eloquent-stereo-msgs
        - ros-eloquent-actionlib-msgs
        - ros-eloquent-shape-msgs
        - ros-eloquent-geometry-msgs
    script: bld_colcon.bat
  - name: ros-eloquent-diagnostic-msgs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-ament-cmake
        - ros-eloquent-geometry-msgs
      run:
        - python
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-geometry-msgs
        - ros-eloquent-rosidl-default-runtime
    script: bld_colcon.bat
  - name: ros-eloquent-geometry-msgs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-std-msgs
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-default-generators
      run:
        - python
        - ros-eloquent-rosidl-default-runtime
        - ros-eloquent-std-msgs
    script: bld_colcon.bat
  - name: ros-eloquent-nav-msgs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-ament-cmake
        - ros-eloquent-geometry-msgs
      run:
        - python
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-geometry-msgs
        - ros-eloquent-rosidl-default-runtime
    script: bld_colcon.bat
  - name: ros-eloquent-sensor-msgs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-ament-cmake
        - ros-eloquent-geometry-msgs
      run:
        - python
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-geometry-msgs
        - ros-eloquent-rosidl-default-runtime
    script: bld_colcon.bat
  - name: ros-eloquent-shape-msgs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-ament-cmake
        - ros-eloquent-geometry-msgs
      run:
        - python
        - ros-eloquent-rosidl-default-runtime
        - ros-eloquent-geometry-msgs
    script: bld_colcon.bat
  - name: ros-eloquent-std-msgs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-default-generators
      run:
        - python
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-rosidl-default-runtime
    script: bld_colcon.bat
  - name: ros-eloquent-std-srvs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-default-generators
      run:
        - python
        - ros-eloquent-rosidl-default-runtime
    script: bld_colcon.bat
  - name: ros-eloquent-stereo-msgs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-sensor-msgs
        - ros-eloquent-std-msgs
        - ros-eloquent-ament-cmake
        - ros-eloquent-rosidl-default-generators
      run:
        - python
        - ros-eloquent-rosidl-default-runtime
        - ros-eloquent-std-msgs
        - ros-eloquent-sensor-msgs
    script: bld_colcon.bat
  - name: ros-eloquent-trajectory-msgs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-ament-cmake
        - ros-eloquent-geometry-msgs
      run:
        - python
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-geometry-msgs
        - ros-eloquent-rosidl-default-runtime
    script: bld_colcon.bat
  - name: ros-eloquent-visualization-msgs
    version: 0.8.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-ament-cmake
        - ros-eloquent-geometry-msgs
      run:
        - python
        - ros-eloquent-builtin-interfaces
        - ros-eloquent-std-msgs
        - ros-eloquent-geometry-msgs
        - ros-eloquent-rosidl-default-runtime
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
