package:
  name: ros
  version: 2020.03.10

source:
  - git_url: https://github.com/ros-gbp/ros_tutorials-release.git
    git_rev: release/noetic/roscpp_tutorials/0.9.2-1
    folder: ros-noetic-roscpp-tutorials/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-roscpp-tutorials
    version: 0.9.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-roscpp-serialization
        - ros-noetic-rostime
        - ros-noetic-std-msgs
      run:
        - boost
        - python {{ python }}
        - ros-noetic-message-runtime
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-roscpp-serialization
        - ros-noetic-rostime
        - ros-noetic-std-msgs
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
