package:
  name: ros
  version: 2020.02.28

source:
  - git_url: https://github.com/ros2-gbp/vision_opencv-release.git
    git_rev: release/eloquent/cv_bridge/2.1.4-1
    folder: ros-eloquent-cv-bridge/src/work
  - git_url: https://github.com/ros2-gbp/vision_opencv-release.git
    git_rev: release/eloquent/image_geometry/2.1.4-1
    folder: ros-eloquent-image-geometry/src/work
  - git_url: https://github.com/ros2-gbp/vision_opencv-release.git
    git_rev: release/eloquent/vision_opencv/2.1.4-1
    folder: ros-eloquent-vision-opencv/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-cv-bridge
    version: 2.1.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - ros-eloquent-sensor-msgs
        - ros-eloquent-python-cmake-module
        - ros-eloquent-ament-cmake-ros
        - numpy
        - opencv 3.4.9
        - colcon-common-extensions
        - python {{ python }}
      run:
        - boost
        - ros-eloquent-sensor-msgs
        - ros-eloquent-ament-index-python
        - numpy
        - opencv 3.4.9
        - python {{ python }}
    script: bld_colcon.bat
  - name: ros-eloquent-image-geometry
    version: 2.1.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-ament-cmake-python
        - ros-eloquent-sensor-msgs
        - ros-eloquent-ament-cmake-ros
        - opencv 3.4.9
        - colcon-common-extensions
        - python {{ python }}
      run:
        - python {{ python }}
        - ros-eloquent-sensor-msgs
        - opencv 3.4.9
    script: bld_colcon.bat
  - name: ros-eloquent-vision-opencv
    version: 2.1.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - python {{ python }}
        - ros-eloquent-ament-cmake
      run:
        - python {{ python }}
        - ros-eloquent-cv-bridge
        - ros-eloquent-image-geometry
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
