package:
  name: ros
  version: 2020.03.12

source:
  - git_url: https://github.com/ros-gbp/urdf_geometry_parser-release.git
    git_rev: release/noetic/urdf_geometry_parser/0.0.3-1
    folder: ros-noetic-urdf-geometry-parser/src/work
  - git_url: https://github.com/ros-gbp/urdf-release.git
    git_rev: release/noetic/urdf_parser_plugin/1.13.2-1
    folder: ros-noetic-urdf-parser-plugin/src/work
  - git_url: https://github.com/ros-gbp/common_msgs-release.git
    git_rev: release/noetic/actionlib_msgs/1.12.7-1
    folder: ros-noetic-actionlib-msgs/src/work
  - git_url: https://github.com/ros-gbp/geometry2-release.git
    git_rev: release/noetic/tf2_msgs/0.7.0-1
    folder: ros-noetic-tf2-msgs/src/work
  - git_url: https://github.com/ros-gbp/common_msgs-release.git
    git_rev: release/noetic/geometry_msgs/1.12.7-1
    folder: ros-noetic-geometry-msgs/src/work
  - git_url: https://github.com/ros-gbp/urdf-release.git
    git_rev: release/noetic/urdf/1.13.2-1
    folder: ros-noetic-urdf/src/work
  - git_url: https://github.com/ros-gbp/rosconsole_bridge-release.git
    git_rev: release/noetic/rosconsole_bridge/0.5.4-1
    folder: ros-noetic-rosconsole-bridge/src/work
  - git_url: https://github.com/ros-gbp/geometry2-release.git
    git_rev: release/noetic/tf2/0.7.0-1
    folder: ros-noetic-tf2/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-urdf-geometry-parser
    version: 0.0.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-roscpp
        - ros-noetic-tf2
        - ros-noetic-urdf
      run:
        - python {{ python }}
        - ros-noetic-roscpp
        - ros-noetic-tf2
        - ros-noetic-urdf
    script: bld_catkin.bat
  - name: ros-noetic-urdf-parser-plugin
    version: 1.13.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - urdfdom_headers
      run:
        - python {{ python }}
        - urdfdom_headers
    script: bld_catkin.bat
  - name: ros-noetic-actionlib-msgs
    version: 1.12.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-tf2-msgs
    version: 0.7.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-actionlib-msgs
        - ros-noetic-catkin
        - ros-noetic-geometry-msgs
        - ros-noetic-message-generation
      run:
        - python {{ python }}
        - ros-noetic-actionlib-msgs
        - ros-noetic-geometry-msgs
        - ros-noetic-message-generation
    script: bld_catkin.bat
  - name: ros-noetic-geometry-msgs
    version: 1.12.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-urdf
    version: 1.13.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cmake-modules
        - ros-noetic-pluginlib
        - ros-noetic-rosconsole-bridge
        - ros-noetic-roscpp
        - ros-noetic-rostest
        - ros-noetic-urdf-parser-plugin
        - tinyxml
        - tinyxml2
        - urdfdom
        - urdfdom_headers
      run:
        - python {{ python }}
        - ros-noetic-pluginlib
        - ros-noetic-rosconsole-bridge
        - ros-noetic-roscpp
        - tinyxml
        - tinyxml2
        - urdfdom
        - urdfdom_headers
    script: bld_catkin.bat
  - name: ros-noetic-rosconsole-bridge
    version: 0.5.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - console_bridge
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cpp-common
        - ros-noetic-rosconsole
      run:
        - console_bridge
        - python {{ python }}
        - ros-noetic-cpp-common
        - ros-noetic-rosconsole
    script: bld_catkin.bat
  - name: ros-noetic-tf2
    version: 0.7.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - console_bridge
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-geometry-msgs
        - ros-noetic-rostime
        - ros-noetic-tf2-msgs
      run:
        - console_bridge
        - python {{ python }}
        - ros-noetic-geometry-msgs
        - ros-noetic-rostime
        - ros-noetic-tf2-msgs
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
