package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/interactive_markers-release.git
    git_rev: release/eloquent/interactive_markers/2.0.1-1
    folder: ros-eloquent-interactive-markers/src/work
  - git_url: https://github.com/ros2-gbp/laser_geometry-release.git
    git_rev: release/eloquent/laser_geometry/2.1.1-1
    folder: ros-eloquent-laser-geometry/src/work
  - git_url: https://github.com/ros2-gbp/resource_retriever-release.git
    git_rev: release/eloquent/libcurl_vendor/2.2.1-1
    folder: ros-eloquent-libcurl-vendor/src/work
  - git_url: https://github.com/ros2-gbp/navigation_msgs-release.git
    git_rev: release/eloquent/map_msgs/2.0.2-1
    folder: ros-eloquent-map-msgs/src/work
  - git_url: https://github.com/ros2-gbp/resource_retriever-release.git
    git_rev: release/eloquent/resource_retriever/2.2.1-1
    folder: ros-eloquent-resource-retriever/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-interactive-markers
    version: 2.0.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-tf2
        - ros-eloquent-rmw
        - ros-eloquent-rclcpp
        - ros-eloquent-ament-cmake-python
        - ros-eloquent-tf2-geometry-msgs
        - ros-eloquent-ament-cmake
        - ros-eloquent-visualization-msgs
      run:
        - python
        - ros-eloquent-rclpy
        - ros-eloquent-rmw
        - ros-eloquent-rclcpp
        - ros-eloquent-visualization-msgs
        - ros-eloquent-tf2-geometry-msgs
        - ros-eloquent-std-msgs
        - ros-eloquent-tf2
        - ros-eloquent-builtin-interfaces
    script: bld_colcon.bat
  - name: ros-eloquent-laser-geometry
    version: 2.1.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - eigen
        - ros-eloquent-rclcpp
        - ros-eloquent-ament-cmake
        - ros-eloquent-eigen3-cmake-module
        - ros-eloquent-sensor-msgs
        - ros-eloquent-tf2
      run:
        - python
        - eigen
        - ros-eloquent-rclcpp
        - ros-eloquent-ament-cmake
        - ros-eloquent-eigen3-cmake-module
        - ros-eloquent-sensor-msgs
        - ros-eloquent-tf2
    script: bld_colcon.bat
  - name: ros-eloquent-libcurl-vendor
    version: 2.2.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
        - libcurl
        - pkg-config
      run:
        - python
        - libcurl
        - pkg-config
    script: bld_colcon.bat
  - name: ros-eloquent-map-msgs
    version: 2.0.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-nav-msgs
        - ros-eloquent-ament-cmake
        - ros-eloquent-std-msgs
        - ros-eloquent-rosidl-default-generators
        - ros-eloquent-sensor-msgs
      run:
        - python
        - ros-eloquent-rosidl-default-runtime
        - ros-eloquent-sensor-msgs
        - ros-eloquent-std-msgs
        - ros-eloquent-nav-msgs
    script: bld_colcon.bat
  - name: ros-eloquent-resource-retriever
    version: 2.2.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-libcurl-vendor
        - ros-eloquent-ament-index-cpp
      run:
        - python
        - ros-eloquent-libcurl-vendor
        - ros-eloquent-ament-index-cpp
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
