package:
  name: ros
  version: 2020.03.03

source:
  - git_url: https://github.com/BehaviorTree/behaviortree_cpp_v3-release.git
    git_rev: release/eloquent/behaviortree_cpp_v3/3.1.1-1
    folder: ros-eloquent-behaviortree-cpp-v3/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-behaviortree-cpp-v3
    version: 3.1.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-ament-cmake-gtest
        - python {{ python }}
        - zeromq
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - zeromq
        - python {{ python }}
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
