package:
  name: ros
  version: 0.0.1

source:
  - url: https://github.com/ros-gbp/catkin-release/archive/release/melodic/catkin/0.7.20-1.tar.gz
    folder: ros-melodic-catkin
    patches:
      - ros-melodic-catkin.patch
  - url: https://github.com/ros-gbp/cmake_modules-release/archive/release/melodic/cmake_modules/0.4.2-0.tar.gz
    folder: ros-melodic-cmake-modules
  - url: https://github.com/ros-gbp/ros_environment-release/archive/release/melodic/ros_environment/1.2.2-1.tar.gz
    folder: ros-melodic-ros-environment
  - url: https://github.com/ros-gbp/rospack-release/archive/release/melodic/rospack/2.5.4-1.tar.gz
    folder: ros-melodic-rospack
    patches:
      - ros-melodic-rospack.patch

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-melodic-catkin
    version: 0.7.20
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - gmock
        - nose
        - mock
        - empy
        - cmake
        - gtest
        - catkin_pkg
      run:
        - python
        - gmock
        - nose
        - mock
        - empy
        - cmake
        - gtest
        - catkin_pkg
    script: bld_.bat
  - name: ros-melodic-cmake-modules
    version: 0.4.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-melodic-catkin
      run:
        - python
        - ros-melodic-catkin
    script: bld_.bat
  - name: ros-melodic-rospack
    version: 2.5.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - tinyxml2
        - coverage
        - ros-melodic-cmake-modules
        - ros-melodic-ros-environment
        - gtest
        - ros-melodic-catkin
        - pkg-config
        - catkin_pkg
        - python
        - boost
        - rosdep
      run:
        - python
        - tinyxml2
        - coverage
        - ros-melodic-cmake-modules
        - ros-melodic-ros-environment
        - gtest
        - ros-melodic-catkin
        - pkg-config
        - catkin_pkg
        - python
        - boost
        - rosdep
    script: bld_.bat
  - name: ros-melodic-ros-environment
    version: 1.2.2
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python
        - ros-melodic-catkin
      run:
        - python
        - ros-melodic-catkin
    script: bld_.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
