package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/kdl_parser-release.git
    git_rev: release/eloquent/kdl_parser/2.2.0-1
    folder: ros-eloquent-kdl-parser/src/work
  - git_url: https://github.com/ros2-gbp/robot_state_publisher-release.git
    git_rev: release/eloquent/robot_state_publisher/2.3.1-1
    folder: ros-eloquent-robot-state-publisher/src/work
  - git_url: https://github.com/ros2-gbp/variants-release.git
    git_rev: release/eloquent/ros_base/0.8.4-1
    folder: ros-eloquent-ros-base/src/work
  - git_url: https://github.com/ros2-gbp/tinyxml_vendor-release.git
    git_rev: release/eloquent/tinyxml_vendor/0.7.0-1
    folder: ros-eloquent-tinyxml-vendor/src/work
  - git_url: https://github.com/ros2-gbp/urdf-release.git
    git_rev: release/eloquent/urdf/2.2.0-1
    folder: ros-eloquent-urdf/src/work
  - git_url: https://github.com/ros2-gbp/urdfdom-release.git
    git_rev: release/eloquent/urdfdom/2.2.0-1
    folder: ros-eloquent-urdfdom/src/work
  - git_url: https://github.com/ros2-gbp/urdfdom_headers-release.git
    git_rev: release/eloquent/urdfdom_headers/1.0.4-1
    folder: ros-eloquent-urdfdom-headers/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-kdl-parser
    version: 2.2.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-orocos-kdl
        - ros-eloquent-tinyxml-vendor
        - tinyxml
        - ros-eloquent-urdf
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-urdfdom-headers
      run:
        - python
        - ros-eloquent-orocos-kdl
        - ros-eloquent-tinyxml-vendor
        - tinyxml
        - ros-eloquent-urdf
        - ros-eloquent-urdfdom-headers
    script: bld_colcon.bat
  - name: ros-eloquent-robot-state-publisher
    version: 2.3.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-orocos-kdl
        - ros-eloquent-ament-cmake
        - ros-eloquent-kdl-parser
        - ros-eloquent-rclcpp
        - ros-eloquent-sensor-msgs
        - ros-eloquent-geometry-msgs
        - ros-eloquent-tf2-ros
        - ros-eloquent-urdf
        - ros-eloquent-urdfdom-headers
      run:
        - python
        - ros-eloquent-orocos-kdl
        - ros-eloquent-kdl-parser
        - ros-eloquent-rclcpp
        - ros-eloquent-sensor-msgs
        - ros-eloquent-geometry-msgs
        - ros-eloquent-tf2-ros
        - ros-eloquent-urdf
        - ros-eloquent-urdfdom-headers
    script: bld_colcon.bat
  - name: ros-eloquent-ros-base
    version: 0.8.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
      run:
        - python
        - ros-eloquent-ros-core
        - ros-eloquent-kdl-parser
        - ros-eloquent-robot-state-publisher
        - ros-eloquent-geometry2
        - ros-eloquent-urdf
    script: bld_colcon.bat
  - name: ros-eloquent-tinyxml-vendor
    version: 0.7.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - cmake
        - tinyxml
      run:
        - python
        - tinyxml
    script: bld_colcon.bat
  - name: ros-eloquent-urdf
    version: 2.2.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-urdfdom
        - ros-eloquent-tinyxml-vendor
        - tinyxml
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-urdfdom-headers
      run:
        - python
        - ros-eloquent-urdfdom
        - ros-eloquent-tinyxml-vendor
        - tinyxml
        - ros-eloquent-urdfdom-headers
    script: bld_colcon.bat
  - name: ros-eloquent-urdfdom
    version: 2.2.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-tinyxml-vendor
        - ros-eloquent-console-bridge-vendor
        - console_bridge
        - cmake
        - tinyxml
        - ros-eloquent-urdfdom-headers
      run:
        - python
        - ros-eloquent-tinyxml-vendor
        - ros-eloquent-console-bridge-vendor
        - console_bridge
        - tinyxml
        - ros-eloquent-urdfdom-headers
    script: bld_colcon.bat
  - name: ros-eloquent-urdfdom-headers
    version: 1.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - cmake
      run:
        - python
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
