package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/fastcdr-release.git
    git_rev: release/eloquent/fastcdr/1.0.11-1
    folder: ros-eloquent-fastcdr/src/work
  - git_url: https://github.com/ros2-gbp/fastrtps-release.git
    git_rev: release/eloquent/fastrtps/1.9.3-1
    folder: ros-eloquent-fastrtps/src/work
  - git_url: https://github.com/ros2-gbp/foonathan_memory_vendor-release.git
    git_rev: release/eloquent/foonathan_memory_vendor/0.3.0-1
    folder: ros-eloquent-foonathan-memory-vendor/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-fastcdr
    version: 1.0.11
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - cmake
      run:
        - python
    script: bld_colcon.bat
  - name: ros-eloquent-fastrtps
    version: 1.9.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - openssl
        - asio
        - ros-eloquent-fastcdr
        - ros-eloquent-foonathan-memory-vendor
        - tinyxml2
        - cmake
      run:
        - python
        - tinyxml2
        - openssl
        - ros-eloquent-fastcdr
        - ros-eloquent-foonathan-memory-vendor
    script: bld_colcon.bat
  - name: ros-eloquent-foonathan-memory-vendor
    version: 0.3.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - cmake
        - git
        - foonathan-memory
      run:
        - python
        - cmake
        - foonathan-memory
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
