package:
  name: ros
  version: 0.0.1

source:
- url: https://github.com/ros-gbp/catkin-release/archive/release/noetic/catkin/0.8.0-1.tar.gz
  folder: ros-noetic-catkin
- url: https://github.com/ros-gbp/cmake_modules-release/archive/release/noetic/cmake_modules/0.5.0-1.tar.gz
  folder: ros-noetic-cmake-modules
- url: https://github.com/ros-gbp/roscpp_core-release/archive/release/noetic/cpp_common/0.7.1-1.tar.gz
  folder: ros-noetic-cpp-common
- url: https://github.com/ros-gbp/ros_environment-release/archive/release/noetic/ros_environment/1.3.0-1.tar.gz
  folder: ros-noetic-ros-environment
- url: https://github.com/ros-gbp/roscpp_core-release/archive/release/noetic/roscpp_core/0.7.1-1.tar.gz
  folder: ros-noetic-roscpp-core
- url: https://github.com/ros-gbp/roscpp_core-release/archive/release/noetic/roscpp_serialization/0.7.1-1.tar.gz
  folder: ros-noetic-roscpp-serialization
- url: https://github.com/ros-gbp/roscpp_core-release/archive/release/noetic/roscpp_traits/0.7.1-1.tar.gz
  folder: ros-noetic-roscpp-traits
- url: https://github.com/ros-gbp/rospack-release/archive/release/noetic/rospack/2.5.5-1.tar.gz
  folder: ros-noetic-rospack
- url: https://github.com/ros-gbp/roscpp_core-release/archive/release/noetic/rostime/0.7.1-1.tar.gz
  folder: ros-noetic-rostime

build:
  number: 0
  skip: true  # [not win64 or not py3k]

outputs:
- name: ros-noetic-catkin
  version: 0.8.0
  requirements:
    build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - cmake
    host:
    - python
    - mock
    - gmock
    - cmake
    - nose
    - gtest
    - empy
    - setuptools
    - catkin_pkg
    run:
    - python
    - mock
    - gmock
    - cmake
    - nose
    - gtest
    - empy
    - setuptools
    - catkin_pkg
  script: bld_.bat
- name: ros-noetic-cmake-modules
  version: 0.5.0
  requirements:
    build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - cmake
    host:
    - python
    - ros-noetic-catkin
    run:
    - python
    - ros-noetic-catkin
  script: bld_.bat
- name: ros-noetic-cpp-common
  version: 0.7.1
  requirements:
    build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - cmake
    host:
    - python
    - console_bridge
    - boost
    - boost
    - ros-noetic-catkin
    run:
    - python
    - console_bridge
    - boost
    - boost
    - ros-noetic-catkin
  script: bld_.bat
- name: ros-noetic-roscpp-serialization
  version: 0.7.1
  requirements:
    build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - cmake
    host:
    - python
    - ros-noetic-cpp-common
    - ros-noetic-rostime
    - ros-noetic-roscpp-traits
    - ros-noetic-catkin
    run:
    - python
    - ros-noetic-cpp-common
    - ros-noetic-rostime
    - ros-noetic-roscpp-traits
    - ros-noetic-catkin
  script: bld_.bat
- name: ros-noetic-roscpp-traits
  version: 0.7.1
  requirements:
    build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - cmake
    host:
    - python
    - ros-noetic-catkin
    - ros-noetic-cpp-common
    - ros-noetic-rostime
    run:
    - python
    - ros-noetic-catkin
    - ros-noetic-cpp-common
    - ros-noetic-rostime
  script: bld_.bat
- name: ros-noetic-rospack
  version: 2.5.5
  requirements:
    build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - cmake
    host:
    - python
    - ros-noetic-ros-environment
    - tinyxml2
    - gtest
    - boost
    - python
    - pkg-config
    - ros-noetic-cmake-modules
    - catkin_pkg
    - rosdep
    - coverage
    - ros-noetic-catkin
    run:
    - python
    - ros-noetic-ros-environment
    - tinyxml2
    - gtest
    - boost
    - python
    - pkg-config
    - ros-noetic-cmake-modules
    - catkin_pkg
    - rosdep
    - coverage
    - ros-noetic-catkin
  script: bld_.bat
- name: ros-noetic-rostime
  version: 0.7.1
  requirements:
    build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - cmake
    host:
    - python
    - boost
    - ros-noetic-cpp-common
    - boost
    - boost
    - ros-noetic-catkin
    run:
    - python
    - boost
    - ros-noetic-cpp-common
    - boost
    - boost
    - ros-noetic-catkin
  script: bld_.bat
- name: ros-noetic-ros-environment
  version: 1.3.0
  requirements:
    build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - cmake
    host:
    - python
    - ros-noetic-catkin
    run:
    - python
    - ros-noetic-catkin
  script: bld_.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
  - seanyen
