package:
  name: ros
  version: 2020.03.11

source:
  - git_url: https://github.com/ros-gbp/qt_gui_core-release.git
    git_rev: release/noetic/qt_gui/0.4.0-1
    folder: ros-noetic-qt-gui/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-qt-gui
    version: 0.4.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - pyqt
        - python {{ python }}
        - qt
        - ros-noetic-catkin
      run:
        - python {{ python }}
        - ros-noetic-python-qt-binding
        - rospkg
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
