package:
  name: ros
  version: 2020.03.03

source:
  - git_url: https://github.com/ros2-gbp/kdl_parser-release.git
    git_rev: release/eloquent/kdl_parser/2.2.0-1
    folder: ros-eloquent-kdl-parser/src/work
  - git_url: https://github.com/ros2-gbp/robot_state_publisher-release.git
    git_rev: release/eloquent/robot_state_publisher/2.3.1-1
    folder: ros-eloquent-robot-state-publisher/src/work
  - git_url: https://github.com/ros2-gbp/urdf-release.git
    git_rev: release/eloquent/urdf/2.2.0-1
    folder: ros-eloquent-urdf/src/work

build:
  number: 1
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-kdl-parser
    version: 2.2.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-tinyxml-vendor
        - python {{ python }}
        - colcon-common-extensions
        - tinyxml
        - ros-eloquent-orocos-kdl
        - urdfdom_headers
        - ros-eloquent-ament-cmake-ros
        - ros-eloquent-urdf
      run:
        - ros-eloquent-tinyxml-vendor
        - python {{ python }}
        - tinyxml
        - ros-eloquent-orocos-kdl
        - urdfdom_headers
        - ros-eloquent-urdf
    script: bld_colcon.bat
  - name: ros-eloquent-robot-state-publisher
    version: 2.3.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-geometry-msgs
        - python {{ python }}
        - colcon-common-extensions
        - ros-eloquent-rclcpp
        - ros-eloquent-orocos-kdl
        - urdfdom_headers
        - ros-eloquent-sensor-msgs
        - ros-eloquent-ament-cmake
        - ros-eloquent-tf2-ros
        - ros-eloquent-kdl-parser
        - ros-eloquent-urdf
      run:
        - ros-eloquent-geometry-msgs
        - python {{ python }}
        - ros-eloquent-rclcpp
        - ros-eloquent-orocos-kdl
        - urdfdom_headers
        - ros-eloquent-sensor-msgs
        - ros-eloquent-tf2-ros
        - ros-eloquent-kdl-parser
        - ros-eloquent-urdf
    script: bld_colcon.bat
  - name: ros-eloquent-urdf
    version: 2.2.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - ros-eloquent-tinyxml-vendor
        - python {{ python }}
        - colcon-common-extensions
        - tinyxml
        - urdfdom_headers
        - urdfdom
        - ros-eloquent-ament-cmake-ros
      run:
        - ros-eloquent-tinyxml-vendor
        - python {{ python }}
        - tinyxml
        - urdfdom_headers
        - urdfdom
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
