package:
  name: ros
  version: 0.0.1

source:
  - git_url: https://github.com/ros2-gbp/rviz-release.git
    git_rev: release/eloquent/rviz2/7.0.4-1
    folder: ros-eloquent-rviz2/src/work
  - git_url: https://github.com/ros2-gbp/rviz-release.git
    git_rev: release/eloquent/rviz_assimp_vendor/7.0.4-1
    folder: ros-eloquent-rviz-assimp-vendor/src/work
  - git_url: https://github.com/ros2-gbp/rviz-release.git
    git_rev: release/eloquent/rviz_common/7.0.4-1
    folder: ros-eloquent-rviz-common/src/work
  - git_url: https://github.com/ros2-gbp/rviz-release.git
    git_rev: release/eloquent/rviz_default_plugins/7.0.4-1
    folder: ros-eloquent-rviz-default-plugins/src/work
  - git_url: https://github.com/ros2-gbp/rviz-release.git
    git_rev: release/eloquent/rviz_ogre_vendor/7.0.4-1
    folder: ros-eloquent-rviz-ogre-vendor/src/work
    patches:
      - patch/ros-eloquent-rviz-ogre-vendor.patch
  - git_url: https://github.com/ros2-gbp/rviz-release.git
    git_rev: release/eloquent/rviz_rendering/7.0.4-1
    folder: ros-eloquent-rviz-rendering/src/work
  - git_url: https://github.com/ros2-gbp/rviz-release.git
    git_rev: release/eloquent/rviz_rendering_tests/7.0.4-1
    folder: ros-eloquent-rviz-rendering-tests/src/work
  - git_url: https://github.com/ros2-gbp/rviz-release.git
    git_rev: release/eloquent/rviz_visual_testing_framework/7.0.4-1
    folder: ros-eloquent-rviz-visual-testing-framework/src/work
  - git_url: https://github.com/ros2-gbp/yaml_cpp_vendor-release.git
    git_rev: release/eloquent/yaml_cpp_vendor/7.0.0-1
    folder: ros-eloquent-yaml-cpp-vendor/src/work
    patches:
      - patch/ros-eloquent-yaml-cpp-vendor.patch

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-rviz2
    version: 7.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-rviz-ogre-vendor
        - ros-eloquent-rviz-common
        - ros-eloquent-ament-cmake
        - qt
      run:
        - python
        - ros-eloquent-rviz-default-plugins
        - ros-eloquent-rviz-ogre-vendor
        - ros-eloquent-rviz-common
    script: bld_colcon.bat
  - name: ros-eloquent-rviz-assimp-vendor
    version: 7.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - assimp
        - ros-eloquent-ament-cmake
      run:
        - python
        - assimp
    script: bld_colcon.bat
  - name: ros-eloquent-rviz-common
    version: 7.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-tf2
        - ros-eloquent-tinyxml-vendor
        - ros-eloquent-rclcpp
        - ros-eloquent-std-msgs
        - ros-eloquent-rviz-ogre-vendor
        - ros-eloquent-resource-retriever
        - ros-eloquent-tf2-geometry-msgs
        - qt
        - ros-eloquent-rviz-rendering
        - ros-eloquent-message-filters
        - ros-eloquent-yaml-cpp-vendor
        - ros-eloquent-geometry-msgs
        - ros-eloquent-tf2-ros
        - ros-eloquent-rviz-assimp-vendor
        - ros-eloquent-ament-cmake
        - ros-eloquent-pluginlib
        - ros-eloquent-sensor-msgs
        - ros-eloquent-urdf
      run:
        - python
        - ros-eloquent-rclcpp
        - ros-eloquent-std-msgs
        - ros-eloquent-rviz-ogre-vendor
        - ros-eloquent-pluginlib
        - ros-eloquent-sensor-msgs
        - qt
        - ros-eloquent-urdf
        - ros-eloquent-tf2
        - ros-eloquent-tf2-geometry-msgs
        - ros-eloquent-message-filters
        - qt
        - ros-eloquent-geometry-msgs
        - ros-eloquent-tf2-ros
        - qt
        - ros-eloquent-tinyxml-vendor
        - ros-eloquent-resource-retriever
        - qt
        - ros-eloquent-yaml-cpp-vendor
        - ros-eloquent-rviz-assimp-vendor
        - ros-eloquent-rviz-rendering
        - qt
    script: bld_colcon.bat
  - name: ros-eloquent-rviz-default-plugins
    version: 7.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-tf2
        - ros-eloquent-interactive-markers
        - ros-eloquent-rclcpp
        - ros-eloquent-tinyxml-vendor
        - ros-eloquent-visualization-msgs
        - ros-eloquent-laser-geometry
        - ros-eloquent-nav-msgs
        - ros-eloquent-tf2-geometry-msgs
        - ros-eloquent-resource-retriever
        - qt
        - ros-eloquent-rviz-rendering
        - ros-eloquent-geometry-msgs
        - ros-eloquent-rviz-common
        - ros-eloquent-tf2-ros
        - ros-eloquent-ament-cmake
        - ros-eloquent-pluginlib
        - ros-eloquent-map-msgs
        - ros-eloquent-urdf
      run:
        - python
        - qt
        - ros-eloquent-tf2
        - ros-eloquent-interactive-markers
        - ros-eloquent-rclcpp
        - ros-eloquent-tinyxml-vendor
        - ros-eloquent-visualization-msgs
        - ros-eloquent-laser-geometry
        - ros-eloquent-nav-msgs
        - ros-eloquent-tf2-geometry-msgs
        - ros-eloquent-resource-retriever
        - ros-eloquent-map-msgs
        - ros-eloquent-rviz-rendering
        - qt
        - ros-eloquent-geometry-msgs
        - ros-eloquent-rviz-common
        - ros-eloquent-tf2-ros
        - ros-eloquent-pluginlib
        - qt
        - qt
        - ros-eloquent-urdf
    script: bld_colcon.bat
  - name: ros-eloquent-rviz-ogre-vendor
    version: 7.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - freetype
        - ros-eloquent-ament-cmake
        - git
        - pkg-config
        - ogre
      run:
        - python
        - freetype
        - freetype
        - ogre
    script: bld_colcon.bat
  - name: ros-eloquent-rviz-rendering
    version: 7.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-rviz-ogre-vendor
        - ros-eloquent-resource-retriever
        - eigen
        - qt
        - ros-eloquent-eigen3-cmake-module
        - ros-eloquent-ament-cmake
        - ros-eloquent-rviz-assimp-vendor
        - ros-eloquent-ament-index-cpp
      run:
        - python
        - qt
        - ros-eloquent-rviz-ogre-vendor
        - ros-eloquent-resource-retriever
        - eigen
        - qt
        - qt
        - ros-eloquent-eigen3-cmake-module
        - ros-eloquent-rviz-assimp-vendor
        - qt
        - ros-eloquent-ament-index-cpp
        - qt
    script: bld_colcon.bat
  - name: ros-eloquent-rviz-rendering-tests
    version: 7.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-rviz-rendering
        - ros-eloquent-resource-retriever
        - ros-eloquent-ament-cmake
        - qt
      run:
        - python
        - ros-eloquent-rviz-rendering
        - ros-eloquent-resource-retriever
    script: bld_colcon.bat
  - name: ros-eloquent-rviz-visual-testing-framework
    version: 7.0.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake-gtest
        - ros-eloquent-rviz-common
        - ros-eloquent-ament-cmake
        - qt
      run:
        - python
        - ros-eloquent-rviz-common
        - ros-eloquent-ament-cmake-gtest
    script: bld_colcon.bat
  - name: ros-eloquent-yaml-cpp-vendor
    version: 7.0.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - colcon-common-extensions
        - ros-eloquent-ament-cmake
        - yaml-cpp
      run:
        - python
        - yaml-cpp
    script: bld_colcon.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
