package:
  name: ros
  version: 2020.03.08

source:
  - git_url: https://github.com/ros-gbp/cmake_modules-release.git
    git_rev: release/noetic/cmake_modules/0.5.0-1
    folder: ros-noetic-cmake-modules/src/work
  - git_url: https://github.com/ros-gbp/ros_environment-release.git
    git_rev: release/noetic/ros_environment/1.3.1-1
    folder: ros-noetic-ros-environment/src/work
  - git_url: https://github.com/ros-gbp/ros-release.git
    git_rev: release/noetic/rosbuild/1.15.0-1
    folder: ros-noetic-rosbuild/src/work
  - git_url: https://github.com/ros-gbp/rosconsole-release.git
    git_rev: release/noetic/rosconsole/1.13.15-1
    folder: ros-noetic-rosconsole/src/work
  - git_url: https://github.com/ros-gbp/ros_comm-release.git
    git_rev: release/noetic/roscpp/1.15.3-1
    folder: ros-noetic-roscpp/src/work
  - git_url: https://github.com/ros-gbp/ros_comm-release.git
    git_rev: release/noetic/rosgraph/1.15.3-1
    folder: ros-noetic-rosgraph/src/work
  - git_url: https://github.com/ros-gbp/ros_comm_msgs-release.git
    git_rev: release/noetic/rosgraph_msgs/1.11.3-1
    folder: ros-noetic-rosgraph-msgs/src/work
  - git_url: https://github.com/ros-gbp/ros-release.git
    git_rev: release/noetic/roslang/1.15.0-1
    folder: ros-noetic-roslang/src/work
  - git_url: https://github.com/ros-gbp/ros-release.git
    git_rev: release/noetic/roslib/1.15.0-1
    folder: ros-noetic-roslib/src/work
  - git_url: https://github.com/ros-gbp/ros-release.git
    git_rev: release/noetic/rosmake/1.15.0-1
    folder: ros-noetic-rosmake/src/work
  - git_url: https://github.com/ros-gbp/rospack-release.git
    git_rev: release/noetic/rospack/2.6.0-1
    folder: ros-noetic-rospack/src/work
  - git_url: https://github.com/ros-gbp/ros_comm-release.git
    git_rev: release/noetic/rospy/1.15.3-1
    folder: ros-noetic-rospy/src/work
  - git_url: https://github.com/ros-gbp/ros-release.git
    git_rev: release/noetic/rosunit/1.15.0-1
    folder: ros-noetic-rosunit/src/work
  - git_url: https://github.com/ros-gbp/std_msgs-release.git
    git_rev: release/noetic/std_msgs/0.5.13-1
    folder: ros-noetic-std-msgs/src/work
  - git_url: https://github.com/ros-gbp/ros_comm-release.git
    git_rev: release/noetic/xmlrpcpp/1.15.3-1
    folder: ros-noetic-xmlrpcpp/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-cmake-modules
    version: 0.5.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - python {{ python }}
    script: bld_catkin.bat
  - name: ros-noetic-rosbuild
    version: 1.15.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - pkg-config
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
      run:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
    script: bld_catkin.bat
  - name: ros-noetic-rosconsole
    version: 1.13.15
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - apr
        - boost
        - log4cxx
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cpp-common
        - ros-noetic-rosbuild
        - ros-noetic-rostime
        - ros-noetic-rosunit
      run:
        - apr
        - boost
        - log4cxx
        - python {{ python }}
        - ros-noetic-cpp-common
        - ros-noetic-rosbuild
        - ros-noetic-rostime
    script: bld_catkin.bat
  - name: ros-noetic-roscpp
    version: 1.15.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - pkg-config
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cpp-common
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-rosconsole
        - ros-noetic-roscpp-serialization
        - ros-noetic-roscpp-traits
        - ros-noetic-rosgraph-msgs
        - ros-noetic-roslang
        - ros-noetic-rostime
        - ros-noetic-std-msgs
        - ros-noetic-xmlrpcpp
      run:
        - boost
        - python {{ python }}
        - ros-noetic-cpp-common
        - ros-noetic-message-runtime
        - ros-noetic-rosconsole
        - ros-noetic-roscpp-serialization
        - ros-noetic-roscpp-traits
        - ros-noetic-rosgraph-msgs
        - ros-noetic-rostime
        - ros-noetic-std-msgs
        - ros-noetic-xmlrpcpp
    script: bld_catkin.bat
  - name: ros-noetic-rosgraph
    version: 1.15.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - mock
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - netifaces
        - python {{ python }}
        - pyyaml
        - rospkg
    script: bld_catkin.bat
  - name: ros-noetic-rosgraph-msgs
    version: 1.11.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-roslang
    version: 1.15.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-genmsg
      run:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-genmsg
    script: bld_catkin.bat
  - name: ros-noetic-roslib
    version: 1.15.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-rosmake
        - ros-noetic-rospack
        - setuptools
      run:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-ros-environment
        - ros-noetic-rospack
        - rospkg
    script: bld_catkin.bat
  - name: ros-noetic-rosmake
    version: 1.15.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - setuptools
      run:
        - python {{ python }}
        - ros-noetic-catkin
        - rospkg
    script: bld_catkin.bat
  - name: ros-noetic-rospack
    version: 2.6.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - coverage
        - gtest
        - pkg-config
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cmake-modules
        - tinyxml2
      run:
        - boost
        - catkin_pkg
        - pkg-config
        - python {{ python }}
        - ros-noetic-ros-environment
        - rosdep
        - tinyxml2
    script: bld_catkin.bat
  - name: ros-noetic-rospy
    version: 1.15.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - numpy
        - python {{ python }}
        - pyyaml
        - ros-noetic-genpy
        - ros-noetic-roscpp
        - ros-noetic-rosgraph
        - ros-noetic-rosgraph-msgs
        - ros-noetic-roslib
        - ros-noetic-std-msgs
        - rospkg
    script: bld_catkin.bat
  - name: ros-noetic-rosunit
    version: 1.15.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - setuptools
      run:
        - python {{ python }}
        - ros-noetic-roslib
        - rospkg
    script: bld_catkin.bat
  - name: ros-noetic-ros-environment
    version: 1.3.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - python {{ python }}
    script: bld_catkin.bat
  - name: ros-noetic-std-msgs
    version: 0.5.13
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
      run:
        - python {{ python }}
        - ros-noetic-message-runtime
    script: bld_catkin.bat
  - name: ros-noetic-xmlrpcpp
    version: 1.15.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cpp-common
        - ros-noetic-rostime
      run:
        - python {{ python }}
        - ros-noetic-cpp-common
        - ros-noetic-rostime
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
